"""Regenerate the cupu_fpu_pkg section of project.vhdl: constants for sin/cos/tan.

All values are computed with exact integer arithmetic at PREC bits.

  TWO_OVER_PI(k)  bit k of 2/pi, weight 2^-k, k = 1..200 used  (Payne-Hanek reduction)
  PI_HALF(j)      bit j of pi/2,  weight 2^-j, j = 0..64 used   (quarter turns -> radians)
  CORDIC_K        prod 1/sqrt(1 + 2^-2i), i = 0..61, Q3.62
  ATAN_ROM(128i+j) bit j of atan(2^-i), i = 0..20 used, Q3.62 (above 20, atan(2^-i) == 2^-i
                  at 62 bits); rows padded to 128 bits

The ROMs are 0-based, one-dimensional and power-of-two sized, because of two GHDL 4.1 bugs
(GHDL 4.1 synthesis is what the TT flow uses):
  - it mis-indexes constant arrays that do not start at 0;
  - its Verilog writer addresses a two-dimensional constant table as {row, column} while packing
    the rows at their real width, so a table with 66-bit rows reads the wrong bits (and past the
    end). GHDL's own simulation is unaffected; the generated Verilog, and so the chip, is not.
"""

from math import isqrt

PREC = 400
ONE = 1 << PREC
FRAC = 62
ITER = 62
ATAN_ROWS = 32   # atan(2^-i) for i < ATAN_ROWS; 32 x 128 bits


def atan_inv(n):
    """atan(1/n) * 2^PREC by the Taylor series."""
    total, term, k, sign = 0, ONE // n, 1, 1
    n2 = n * n
    while term:
        total += sign * (term // k)
        term //= n2
        k += 2
        sign = -sign
    return total


PI = 4 * (4 * atan_inv(5) - atan_inv(239))  # Machin


def q62(x):
    """PREC-bit fixed point -> Q3.62, round to nearest."""
    return (x + (1 << (PREC - FRAC - 1))) >> (PREC - FRAC)


def bits(value, first, last):
    """Bits first..last of a PREC-bit fraction (bit k has weight 2^-k; bit 0 is the ones place)."""
    return "".join(str((value >> (PREC - k)) & 1) for k in range(first, last + 1))


def main():
    two_over_pi = (2 * ONE * ONE) // PI
    pi_half = PI // 2

    k2 = ONE  # K^2 = prod 1 / (1 + 2^-2i)
    for i in range(ITER):
        k2 = k2 * ONE // (ONE + (ONE >> (2 * i)))
    cordic_k = isqrt(k2 * ONE)

    atans = [PI // 4] + [atan_inv(1 << i) for i in range(1, ATAN_ROWS)]
    for i in range(21, ITER):
        assert q62(atan_inv(1 << i)) == 1 << (FRAC - i), i

    out = []
    w = out.append
    w("-- Generated by gen_fpu_pkg.py, do not edit.")
    w("library ieee;")
    w("use ieee.std_logic_1164.all;")
    w("use ieee.numeric_std.all;")
    w("")
    w("package cupu_fpu_pkg is")
    w(f'  constant TWO_OVER_PI : std_logic_vector(0 to 255) := "{bits(two_over_pi, 0, 255)}";')
    w(f'  constant PI_HALF     : std_logic_vector(0 to 127) := "{bits(pi_half, 0, 127)}";')
    w(f'  constant CORDIC_K    : unsigned(65 downto 0) := "{q62(cordic_k):066b}";')
    w(f"  constant ATAN_ROM    : std_logic_vector(0 to {128 * ATAN_ROWS - 1}) :=")
    for i, a in enumerate(atans):
        row = "".join(str((q62(a) >> j) & 1) for j in range(128))   # index 128 i + j = bit j
        w(f'    "{row}"{" &" if i < ATAN_ROWS - 1 else ";"}')
    w("end package;")

    begin, end = "-- BEGIN cupu_fpu_pkg (generated by gen_fpu_pkg.py)\n", "-- END cupu_fpu_pkg\n"
    head, rest = open("project.vhdl").read().split(begin)
    tail = rest.split(end)[1]
    with open("project.vhdl", "w") as f:
        f.write(head + begin + "\n".join(out) + "\n" + end + tail)
    print(f"K = {cordic_k / ONE:.20f}, pi = {PI / ONE:.20f}")


if __name__ == "__main__":
    main()
