"""Generate cupu_fpu_pkg.vhd: constants for the FPU's sin/cos/tan.

All values are computed with exact integer arithmetic at PREC bits.

  TWO_OVER_PI(k)  bit k of 2/pi, weight 2^-k, k = 1..200  (Payne-Hanek reduction)
  PI_HALF(j)      bit j of pi/2,  weight 2^-j, j = 0..64  (quarter turns -> radians)
  CORDIC_K        prod 1/sqrt(1 + 2^-2i), i = 0..61, Q3.62
  ATAN_TAB(i)     atan(2^-i), i = 0..20, Q3.62 (above 20, atan(2^-i) == 2^-i at 62 bits)
"""

from math import isqrt

PREC = 400
ONE = 1 << PREC
FRAC = 62
ITER = 62
ATAN_N = 21


def atan_inv(n):
    """atan(1/n) * 2^PREC by the Taylor series."""
    total, term, k, sign = 0, ONE // n, 1, 1
    n2 = n * n
    while term:
        total += sign * (term // k)
        term //= n2
        k += 2
        sign = -sign
    return total


PI = 4 * (4 * atan_inv(5) - atan_inv(239))  # Machin


def q62(x):
    """PREC-bit fixed point -> Q3.62, round to nearest."""
    return (x + (1 << (PREC - FRAC - 1))) >> (PREC - FRAC)


def bits(value, first, last):
    """Bits first..last of a PREC-bit fraction (bit k has weight 2^-k; bit 0 is the ones place)."""
    return "".join(str((value >> (PREC - k)) & 1) for k in range(first, last + 1))


def main():
    two_over_pi = (2 * ONE * ONE) // PI
    pi_half = PI // 2

    k2 = ONE  # K^2 = prod 1 / (1 + 2^-2i)
    for i in range(ITER):
        k2 = k2 * ONE // (ONE + (ONE >> (2 * i)))
    cordic_k = isqrt(k2 * ONE)

    atans = [PI // 4] + [atan_inv(1 << i) for i in range(1, ATAN_N)]
    for i in range(ATAN_N, ITER):
        assert q62(atan_inv(1 << i)) == 1 << (FRAC - i), i

    out = []
    w = out.append
    w("-- Generated by gen_fpu_pkg.py, do not edit.")
    w("library ieee;")
    w("use ieee.std_logic_1164.all;")
    w("use ieee.numeric_std.all;")
    w("")
    w("package cupu_fpu_pkg is")
    w(f'  constant TWO_OVER_PI : std_logic_vector(1 to 200) := "{bits(two_over_pi, 1, 200)}";')
    w(f'  constant PI_HALF     : std_logic_vector(0 to 64) := "{bits(pi_half, 0, 64)}";')
    w(f'  constant CORDIC_K    : unsigned(65 downto 0) := "{q62(cordic_k):066b}";')
    w(f"  type atan_tab_t is array (0 to {ATAN_N - 1}) of unsigned(65 downto 0);")
    w("  constant ATAN_TAB : atan_tab_t := (")
    for i, a in enumerate(atans):
        w(f'    "{q62(a):066b}"{"," if i < ATAN_N - 1 else ""}')
    w("  );")
    w("end package;")

    with open("cupu_fpu_pkg.vhd", "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"K = {cordic_k / ONE:.20f}, pi = {PI / ONE:.20f}")


if __name__ == "__main__":
    main()
