-- CUPU-II "Stollentroll" for Tiny Tapeout: package, FPU, SPI memory controller,
-- CPU core and the tt_um top level (last, so it is the unit ghdl elaborates).

-- BEGIN cupu_fpu_pkg (generated by gen_fpu_pkg.py)
-- Generated by gen_fpu_pkg.py, do not edit.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package cupu_fpu_pkg is
  constant TWO_OVER_PI : std_logic_vector(0 to 255) := "0101000101111100110000011011011100100111001000100000101010010100111111100001001110101011111010001111101010011010011011101110000001101101101100010100101011001100100111100010000111001000001000001111111100101000101100011101010111101111010111011110001010110000";
  constant PI_HALF     : std_logic_vector(0 to 127) := "11001001000011111101101010100010001000010110100011000010001101001100010011000110011000101000101110000000110111000001110011010001";
  constant CORDIC_K    : unsigned(65 downto 0) := "000010011011011101001110110110101000010000110101111001011010011010";
  type atan_tab_t is array (0 to 31) of unsigned(65 downto 0);
  constant ATAN_TAB : atan_tab_t := (
    "000011001001000011111101101010100010001000010110100011000010001101",
    "000001110110101100011001110000010101100001101110110100111101101001",
    "000000111110101101101110101111110010010110010000000110111010110001",
    "000000011111110101011011101010011010101011000010111101101101110010",
    "000000001111111110101010110111011011100101100111111011110100111001",
    "000000000111111111110101010101101110111010100101110110001001001011",
    "000000000011111111111110101010101011011101110110111001010011010110",
    "000000000001111111111111110101010101010110111011101110101001011101",
    "000000000000111111111111111110101010101010101101110111011101101110",
    "000000000000011111111111111111110101010101010101011011101110111100",
    "000000000000001111111111111111111110101010101010101010110111011110",
    "000000000000000111111111111111111111110101010101010101010101101111",
    "000000000000000011111111111111111111111110101010101010101010101011",
    "000000000000000001111111111111111111111111110101010101010101010101",
    "000000000000000000111111111111111111111111111110101010101010101011",
    "000000000000000000011111111111111111111111111111110101010101010101",
    "000000000000000000001111111111111111111111111111111110101010101011",
    "000000000000000000000111111111111111111111111111111111110101010101",
    "000000000000000000000011111111111111111111111111111111111110101011",
    "000000000000000000000001111111111111111111111111111111111111110101",
    "000000000000000000000000111111111111111111111111111111111111111111",
    "000000000000000000000000100000000000000000000000000000000000000000",
    "000000000000000000000000010000000000000000000000000000000000000000",
    "000000000000000000000000001000000000000000000000000000000000000000",
    "000000000000000000000000000100000000000000000000000000000000000000",
    "000000000000000000000000000010000000000000000000000000000000000000",
    "000000000000000000000000000001000000000000000000000000000000000000",
    "000000000000000000000000000000100000000000000000000000000000000000",
    "000000000000000000000000000000010000000000000000000000000000000000",
    "000000000000000000000000000000001000000000000000000000000000000000",
    "000000000000000000000000000000000100000000000000000000000000000000",
    "000000000000000000000000000000000010000000000000000000000000000000"
  );
end package;
-- END cupu_fpu_pkg

-------------------------------------------------------------------------------

-- CUPU-II floating point unit: IEEE 754 binary32, round to nearest even.
--
--   op  func  operation
--   0   0x0E  itof   int32 -> float
--   1   0x0F  ftoi   float -> int32, round half away from zero (Go math.Round);
--                    NaN, inf and out of range give 0x80000000
--   2   0x10  fadd
--   3   0x11  fsub
--   4   0x12  fmul
--   5   0x13  fdiv
--   6   0x14  sqrt
--   7   0x15  sin
--   8   0x16  cos
--   9   0x17  tan
--
-- Everything is sequential around one 67-bit adder. Results are exact (correctly rounded)
-- for itof/ftoi/fadd/fsub/fmul/fdiv/sqrt, subnormals included. sin/cos/tan use Payne-Hanek
-- argument reduction and a 62-step CORDIC with 62 fraction bits; they are within 1 ulp and
-- almost always correctly rounded. Every NaN result is 0x7FC00000.
--
-- a and b must stay stable from start until done.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.cupu_fpu_pkg.all;

entity cupu_fpu is
  port (
    clk   : in  std_logic;
    rst   : in  std_logic;
    start : in  std_logic;                     -- one-cycle pulse
    op    : in  unsigned(3 downto 0);
    a     : in  std_logic_vector(31 downto 0);
    b     : in  std_logic_vector(31 downto 0);
    res   : out std_logic_vector(31 downto 0);
    done  : out std_logic                      -- one-cycle pulse, res valid with it
  );
end entity;

architecture rtl of cupu_fpu is
  constant OP_ITOF : natural := 0;
  constant OP_FTOI : natural := 1;
  constant OP_FADD : natural := 2;
  constant OP_FSUB : natural := 3;
  constant OP_FMUL : natural := 4;
  constant OP_FDIV : natural := 5;
  constant OP_SQRT : natural := 6;
  constant OP_SIN  : natural := 7;
  constant OP_COS  : natural := 8;
  constant OP_TAN  : natural := 9;

  constant QNAN    : std_logic_vector(31 downto 0) := x"7FC00000";
  constant ONE_F   : std_logic_vector(31 downto 0) := x"3F800000";
  constant ONE_Q62 : unsigned(65 downto 0) := shift_left(to_unsigned(1, 66), 62);

  type state_t is (
    F_IDLE, F_PRENORM,
    F_ADD_ALIGN, F_ADD_SUM,
    F_FTOI_SHIFT, F_FTOI_RND, F_FTOI_NEG,
    F_MUL, F_DIV, F_SQRT,
    F_TRIG_SMALL, F_PH, F_PH_SHIFT, F_PH_DONE, F_PIMUL, F_TRIG_START,
    F_CA, F_CB, F_CC, F_TRIG_OUT, F_TAN1, F_TAN2,
    F_NORM, F_ROUND, F_DONE
  );
  -- where F_NORM goes when it is done
  type cont_t is (C_ROUND, C_TAN1, C_TAN2);

  subtype exp_t is integer range -1024 to 1023;

  signal state : state_t;
  signal cont  : cont_t;
  signal opn   : natural range 0 to 15;

  signal R, X, Y, Z : unsigned(65 downto 0);
  signal W          : unsigned(91 downto 0);  -- Payne-Hanek accumulator, CORDIC temp
  signal ma, mb     : unsigned(23 downto 0);
  signal ea, eb     : exp_t;
  signal er, ed     : exp_t;  -- R's LSB has weight 2^(er - 65)
  signal sr, stk    : std_logic;
  signal effsub     : std_logic;
  signal cnt        : unsigned(7 downto 0);
  signal quad       : unsigned(1 downto 0);
  signal res_r      : std_logic_vector(31 downto 0);
  signal done_r     : std_logic;

  -- unpacked operands
  signal a_exp, b_exp   : unsigned(7 downto 0);
  signal a_m, b_m       : unsigned(23 downto 0);
  signal a_e, b_e       : exp_t;
  signal a_nan, b_nan   : std_logic;
  signal a_inf, b_inf   : std_logic;
  signal a_zero, b_zero : std_logic;
  signal sa, sb, sbe    : std_logic;

  -- shared adder: add_s = add_x + (add_y xor inv) + inv
  signal add_x, add_y : unsigned(65 downto 0);
  signal add_inv      : std_logic;
  signal add_s        : unsigned(66 downto 0);
  signal add_ge       : std_logic;  -- carry out: add_x >= add_y when subtracting

  signal shifted : unsigned(65 downto 0);  -- CORDIC: X or Y >>> i
  signal atan_i  : unsigned(65 downto 0);

  -- which CORDIC output F_TRIG_OUT / F_TAN1 convert: '1' = Y (sin r), '0' = X (cos r)
  signal is_sin, is_cos, is_tan, in_out, trig_use_y : std_logic;

  function unpack_e(e : unsigned(7 downto 0)) return exp_t is
  begin
    if e = 0 then
      return -126;
    end if;
    return to_integer(e) - 127;
  end function;
begin
  res  <= res_r;
  done <= done_r;
  opn  <= to_integer(op);

  a_exp  <= unsigned(a(30 downto 23));
  b_exp  <= unsigned(b(30 downto 23));
  a_m(23) <= '0' when a_exp = 0 else '1';  -- hidden bit
  b_m(23) <= '0' when b_exp = 0 else '1';
  a_m(22 downto 0) <= unsigned(a(22 downto 0));
  b_m(22 downto 0) <= unsigned(b(22 downto 0));
  a_e    <= unpack_e(a_exp);
  b_e    <= unpack_e(b_exp);
  a_nan  <= '1' when a_exp = 255 and unsigned(a(22 downto 0)) /= 0 else '0';
  b_nan  <= '1' when b_exp = 255 and unsigned(b(22 downto 0)) /= 0 else '0';
  a_inf  <= '1' when a_exp = 255 and unsigned(a(22 downto 0)) = 0 else '0';
  b_inf  <= '1' when b_exp = 255 and unsigned(b(22 downto 0)) = 0 else '0';
  a_zero <= '1' when unsigned(a(30 downto 0)) = 0 else '0';
  b_zero <= '1' when unsigned(b(30 downto 0)) = 0 else '0';
  sa     <= a(31);
  sb     <= b(31);
  sbe    <= b(31) xor '1' when opn = OP_FSUB else b(31);

  -- plain std_logic on purpose: GHDL 4.1 synthesis got the boolean version of this wrong
  is_sin <= '1' when opn = OP_SIN else '0';
  is_cos <= '1' when opn = OP_COS else '0';
  is_tan <= '1' when opn = OP_TAN else '0';
  in_out <= '1' when state = F_TRIG_OUT else '0';
  -- sin: q even Y, odd X; cos: q even X, odd Y
  -- tan: denominator (F_TRIG_OUT) q even X, odd Y; numerator (F_TAN1) the other one
  trig_use_y <= (is_sin and not quad(0)) or (is_cos and quad(0)) or
                (is_tan and not (in_out xor quad(0)));

  shifted <= unsigned(shift_right(signed(Y), to_integer(cnt(5 downto 0)))) when state = F_CA else
             unsigned(shift_right(signed(X), to_integer(cnt(5 downto 0))));

  process (cnt)
  begin
    if cnt <= 20 then
      atan_i <= ATAN_TAB(to_integer(cnt(4 downto 0)));
    elsif cnt > 62 then
      atan_i <= (others => '0');
    else
      atan_i <= shift_left(to_unsigned(1, 66), 62 - to_integer(cnt(5 downto 0)));
    end if;
  end process;

  ---------------------------------------------------------------------------
  -- shared adder operands
  ---------------------------------------------------------------------------
  process (state, opn, a, R, X, Y, Z, W, ma, mb, stk, effsub, cnt, shifted, atan_i, trig_use_y)
    variable v : unsigned(65 downto 0);
  begin
    add_x   <= (others => '0');
    add_y   <= (others => '0');
    add_inv <= '0';
    case state is
      when F_IDLE =>                              -- itof: |a|
        add_y   <= unsigned(resize(signed(a), 66));
        add_inv <= a(31);
      when F_ADD_SUM =>
        add_x   <= R;
        add_y   <= X;
        add_inv <= effsub;
      when F_FTOI_RND =>
        add_x    <= X;
        add_y(0) <= stk;
      when F_FTOI_NEG =>
        add_y   <= X;
        add_inv <= sa;
      when F_MUL =>
        add_x <= resize(X(47 downto 24), 66);
        if Y(0) = '1' then
          add_y <= resize(mb, 66);
        end if;
      when F_DIV =>
        add_x   <= resize(X(34 downto 0), 66);
        add_y   <= resize(Y(34 downto 0), 66);
        add_inv <= '1';
      when F_SQRT =>
        add_x   <= resize(Y(31 downto 0) & X(55 downto 54), 66);
        add_y   <= resize(Z(27 downto 0) & "01", 66);
        add_inv <= '1';
      when F_PH =>
        add_x <= resize(W(91 downto 68), 66);
        if TWO_OVER_PI(to_integer(cnt)) = '1' then
          add_y <= resize(ma, 66);
        end if;
      when F_PIMUL =>
        add_x <= unsigned(shift_right(signed(Z), 1));
        if PI_HALF(to_integer(cnt(6 downto 0))) = '1' then
          add_y <= X;
        end if;
      -- CORDIC step, rotating towards z = 0:
      --   z >= 0: x -= y>>i, y += x>>i, z -= atan(2^-i)
      --   z <  0: x += y>>i, y -= x>>i, z += atan(2^-i)
      when F_CA =>
        add_x   <= X;
        add_y   <= shifted;
        add_inv <= not Z(65);
      when F_CB =>
        add_x   <= Y;
        add_y   <= shifted;
        add_inv <= Z(65);
      when F_CC =>
        add_x   <= Z;
        add_y   <= atan_i;
        add_inv <= not Z(65);
      when F_TRIG_OUT | F_TAN1 =>
        -- |value| to convert: sin/cos result, or tan's denominator (F_TRIG_OUT)
        -- and numerator (F_TAN1). X = cos r, Y = sin r.
        if trig_use_y = '1' then
          v := Y;
        else
          v := X;
        end if;
        add_y   <= v;
        add_inv <= v(65);
      when others => null;
    end case;
  end process;

  process (add_x, add_y, add_inv)
    variable yy : unsigned(65 downto 0);
    variable c  : unsigned(66 downto 0);
  begin
    yy := add_y;
    if add_inv = '1' then
      yy := not add_y;
    end if;
    c := (0 => add_inv, others => '0');
    add_s <= ('0' & add_x) + ('0' & yy) + c;
  end process;
  add_ge <= add_s(66);

  ---------------------------------------------------------------------------
  -- control
  ---------------------------------------------------------------------------
  process (clk)
    variable big_is_a : boolean;
    variable d        : exp_t;
    variable t        : exp_t;
    variable mant     : unsigned(24 downto 0);
    variable inc      : std_logic;
    variable sticky   : std_logic;
    variable e2       : exp_t;
    variable v        : unsigned(65 downto 0);
    variable nsign    : std_logic;
    variable dsign    : std_logic;
  begin
    if rising_edge(clk) then
      done_r <= '0';
      if rst = '1' then
        state <= F_IDLE;
      else
        case state is
          -------------------------------------------------------------------
          when F_IDLE =>
            stk  <= '0';
            cont <= C_ROUND;
            ma   <= a_m;
            mb   <= b_m;
            ea   <= a_e;
            eb   <= b_e;
            if start = '1' then
              state <= F_DONE;  -- default for the special cases below
              case opn is
                when OP_ITOF =>
                  if a = x"00000000" then
                    res_r <= (others => '0');
                  else
                    sr    <= a(31);
                    R     <= add_s(65 downto 0);
                    er    <= 65;
                    state <= F_NORM;
                  end if;

                when OP_FTOI =>
                  if a_exp >= 158 then            -- |a| >= 2^31, inf, NaN
                    res_r <= x"80000000";
                  elsif a_exp < 126 then          -- |a| < 0.5
                    res_r <= (others => '0');
                  else
                    X     <= resize(a_m & x"00", 66);
                    cnt   <= to_unsigned(158, 8) - a_exp;
                    state <= F_FTOI_SHIFT;
                  end if;

                when OP_FADD | OP_FSUB =>
                  if a_nan = '1' or b_nan = '1' or (a_inf = '1' and b_inf = '1' and sa /= sbe) then
                    res_r <= QNAN;
                  elsif a_inf = '1' then
                    res_r <= sa & a(30 downto 0);
                  elsif b_inf = '1' then
                    res_r <= sbe & b(30 downto 0);
                  else
                    big_is_a := unsigned(a(30 downto 0)) >= unsigned(b(30 downto 0));
                    R <= (others => '0');
                    X <= (others => '0');
                    if big_is_a then
                      R(64 downto 41) <= a_m;
                      X(64 downto 41) <= b_m;
                      er <= a_e + 1;
                      sr <= sa;
                      d  := a_e - b_e;
                    else
                      R(64 downto 41) <= b_m;
                      X(64 downto 41) <= a_m;
                      er <= b_e + 1;
                      sr <= sbe;
                      d  := b_e - a_e;
                    end if;
                    if d > 50 then
                      d := 50;
                    end if;
                    cnt    <= to_unsigned(d, 8);
                    effsub <= sa xor sbe;
                    state  <= F_ADD_ALIGN;
                  end if;

                when OP_FMUL =>
                  sr <= sa xor sb;
                  if a_nan = '1' or b_nan = '1' or (a_inf = '1' and b_zero = '1') or (a_zero = '1' and b_inf = '1') then
                    res_r <= QNAN;
                  elsif a_inf = '1' or b_inf = '1' then
                    res_r <= (sa xor sb) & "1111111100000000000000000000000";
                  elsif a_zero = '1' or b_zero = '1' then
                    res_r <= (sa xor sb) & "0000000000000000000000000000000";
                  else
                    state <= F_PRENORM;
                  end if;

                when OP_FDIV =>
                  sr <= sa xor sb;
                  if a_nan = '1' or b_nan = '1' or (a_inf = '1' and b_inf = '1') or (a_zero = '1' and b_zero = '1') then
                    res_r <= QNAN;
                  elsif a_inf = '1' or b_zero = '1' then
                    res_r <= (sa xor sb) & "1111111100000000000000000000000";
                  elsif a_zero = '1' or b_inf = '1' then
                    res_r <= (sa xor sb) & "0000000000000000000000000000000";
                  else
                    state <= F_PRENORM;
                  end if;

                when OP_SQRT =>
                  sr <= '0';
                  mb <= x"800000";
                  if a_nan = '1' or (sa = '1' and a_zero = '0') then
                    res_r <= QNAN;
                  elsif a_zero = '1' or a_inf = '1' then
                    res_r <= a;
                  else
                    state <= F_PRENORM;
                  end if;

                when OP_SIN | OP_COS | OP_TAN =>
                  if a_nan = '1' or a_inf = '1' then
                    res_r <= QNAN;
                  elsif a_exp < 115 then          -- |a| < 2^-12
                    if opn = OP_COS then
                      res_r <= ONE_F;
                    else
                      res_r <= a;
                    end if;
                  elsif a_exp < 126 then          -- |a| < 0.5: no reduction needed
                    Z     <= resize(a_m, 66);
                    cnt   <= a_exp - 88;          -- Q3.62: m * 2^(exp - 150 + 62)
                    quad  <= "00";
                    state <= F_TRIG_SMALL;
                  else
                    W     <= (others => '0');
                    cnt   <= a_exp - 58;          -- highest 2/pi bit that matters
                    state <= F_PH;
                  end if;

                when others =>
                  res_r <= QNAN;
              end case;
            end if;

          -------------------------------------------------------------------
          when F_PRENORM =>
            -- make subnormal mantissas start with 1
            if ma(23) = '0' then
              ma <= ma(22 downto 0) & '0';
              ea <= ea - 1;
            elsif mb(23) = '0' then
              mb <= mb(22 downto 0) & '0';
              eb <= eb - 1;
            else
              case opn is
                when OP_FMUL =>
                  X     <= (others => '0');
                  Y     <= resize(ma, 66);
                  cnt   <= to_unsigned(24, 8);
                  state <= F_MUL;
                when OP_FDIV =>
                  X     <= resize(ma & "0000000000", 66);
                  Y     <= resize(mb & "0000000000", 66);
                  R     <= (others => '0');
                  er    <= ea - eb + 38;
                  cnt   <= to_unsigned(28, 8);
                  state <= F_DIV;
                when others =>                    -- sqrt
                  if ea mod 2 = 0 then
                    X  <= shift_left(resize(ma, 66), 31);
                    er <= ea / 2 + 38;
                  else
                    X  <= shift_left(resize(ma, 66), 32);
                    er <= (ea - 1) / 2 + 38;
                  end if;
                  Y     <= (others => '0');
                  Z     <= (others => '0');
                  cnt   <= to_unsigned(28, 8);
                  state <= F_SQRT;
              end case;
            end if;

          -------------------------------------------------------------------
          when F_ADD_ALIGN =>
            -- shift the smaller operand right, folding lost bits into bit 0
            if cnt = 0 then
              state <= F_ADD_SUM;
            else
              X   <= '0' & X(65 downto 2) & (X(1) or X(0));
              cnt <= cnt - 1;
            end if;

          when F_ADD_SUM =>
            R <= add_s(65 downto 0);
            if add_s(65 downto 0) = 0 then
              sr <= sa and sbe;  -- exact zero: -0 only for (-0) + (-0)
            end if;
            state <= F_NORM;

          -------------------------------------------------------------------
          when F_FTOI_SHIFT =>
            if cnt = 0 then
              state <= F_FTOI_RND;
            else
              X   <= '0' & X(65 downto 1);
              stk <= X(0);  -- last bit shifted out = the 0.5 bit
              cnt <= cnt - 1;
            end if;

          when F_FTOI_RND =>
            X     <= add_s(65 downto 0);
            state <= F_FTOI_NEG;

          when F_FTOI_NEG =>
            res_r <= std_logic_vector(add_s(31 downto 0));
            state <= F_DONE;

          -------------------------------------------------------------------
          when F_MUL =>
            -- shift-add: X(47:0) accumulates ma * mb, Y feeds ma's bits LSB first
            if cnt = 0 then
              R     <= X;
              er    <= ea + eb + 19;
              state <= F_NORM;
            else
              X(47 downto 0) <= add_s(24 downto 0) & X(23 downto 1);
              Y   <= '0' & Y(65 downto 1);
              cnt <= cnt - 1;
            end if;

          when F_DIV =>
            -- restoring division; quotient bits shift into R
            if cnt = 0 then
              if X /= 0 then
                stk <= '1';
              end if;
              state <= F_NORM;
            else
              R <= R(64 downto 0) & add_ge;
              if add_ge = '1' then
                X <= add_s(64 downto 0) & '0';
              else
                X <= X(64 downto 0) & '0';
              end if;
              cnt <= cnt - 1;
            end if;

          when F_SQRT =>
            -- digit by digit: two radicand bits per step from X, remainder Y, root Z
            if cnt = 0 then
              R <= Z;
              if Y /= 0 then
                stk <= '1';
              end if;
              state <= F_NORM;
            else
              if add_ge = '1' then
                Y <= add_s(65 downto 0);
              else
                Y <= resize(Y(31 downto 0) & X(55 downto 54), 66);
              end if;
              Z   <= Z(64 downto 0) & add_ge;
              X   <= X(63 downto 0) & "00";
              cnt <= cnt - 1;
            end if;

          -------------------------------------------------------------------
          -- sin / cos / tan
          -------------------------------------------------------------------
          when F_TRIG_SMALL =>
            if cnt = 0 then
              state <= F_TRIG_START;
            else
              Z   <= Z(64 downto 0) & '0';
              cnt <= cnt - 1;
            end if;

          when F_PH =>
            -- Payne-Hanek: W = sum of 2/pi bits * mantissa, LSB first, giving
            -- |a| * 2/pi mod 4 in Q2.66 (W(67 downto 0)) at the end
            W <= add_s(24 downto 0) & W(67 downto 1);
            t := to_integer(a_exp) - 151;       -- lowest bit that matters, at least 1
            if t < 1 then
              t := 1;
            end if;
            if to_integer(cnt) = t then
              if a_exp < 152 then
                cnt <= to_unsigned(152, 8) - a_exp;
              else
                cnt <= (others => '0');
              end if;
              state <= F_PH_SHIFT;
            else
              cnt <= cnt - 1;
            end if;

          when F_PH_SHIFT =>
            if cnt = 0 then
              state <= F_PH_DONE;
            else
              W   <= '0' & W(91 downto 1);
              cnt <= cnt - 1;
            end if;

          when F_PH_DONE =>
            -- nearest quadrant, and the signed remainder in [-0.5, 0.5) quarter turns
            quad  <= W(67 downto 66) + ("0" & W(65));
            X     <= unsigned(shift_right(signed(W(65 downto 0)), 4));  -- Q3.62
            Z     <= (others => '0');
            cnt   <= to_unsigned(64, 8);
            state <= F_PIMUL;

          when F_PIMUL =>
            -- Z = X * pi/2, pi/2's bits LSB first
            Z <= add_s(65 downto 0);
            if cnt = 0 then
              state <= F_TRIG_START;
            else
              cnt <= cnt - 1;
            end if;

          when F_TRIG_START =>
            -- Z = reduced angle r in radians, |r| <= pi/4
            if Z(65 downto 42) = 0 or not Z(65 downto 42) = 0 then
              X     <= ONE_Q62;     -- |r| < 2^-20: cos r = 1, sin r = r to well below 1 ulp
              Y     <= Z;
              state <= F_TRIG_OUT;
            else
              X     <= CORDIC_K;
              Y     <= (others => '0');
              cnt   <= (others => '0');
              state <= F_CA;
            end if;

          when F_CA =>
            W(65 downto 0) <= add_s(65 downto 0);   -- new X, parked
            state          <= F_CB;

          when F_CB =>
            Y     <= add_s(65 downto 0);
            state <= F_CC;

          when F_CC =>
            X <= W(65 downto 0);
            Z <= add_s(65 downto 0);
            if cnt = 61 then
              state <= F_TRIG_OUT;
            else
              cnt   <= cnt + 1;
              state <= F_CA;
            end if;

          when F_TRIG_OUT =>
            -- sin: q0 +sin q1 +cos q2 -sin q3 -cos, then odd in a
            -- cos: q0 +cos q1 -sin q2 -cos q3 +sin
            -- tan: q even +sin/cos, q odd -cos/sin, then odd in a
            -- the adder is already producing |value| (see operand process)
            if opn = OP_TAN then
              if quad(0) = '0' then
                nsign := Y(65);
                dsign := X(65);
              else
                nsign := X(65);
                dsign := Y(65);
              end if;
              sr   <= nsign xor dsign xor quad(0) xor sa;
              cont <= C_TAN1;                 -- normalise the denominator first
            elsif opn = OP_SIN then
              if quad(0) = '0' then v := Y; else v := X; end if;
              sr <= v(65) xor quad(1) xor sa;
            else
              if quad(0) = '0' then v := X; else v := Y; end if;
              sr <= v(65) xor (quad(1) xor quad(0));
            end if;
            R     <= add_s(65 downto 0);
            er    <= 3;
            stk   <= '0';
            state <= F_NORM;

          when F_TAN1 =>
            -- normalised denominator is in R; park it in Z, normalise the numerator
            Z     <= R;
            ed    <= er;
            R     <= add_s(65 downto 0);
            er    <= 3;
            cont  <= C_TAN2;
            state <= F_NORM;

          when F_TAN2 =>
            X     <= resize(R(65 downto 32), 66);
            Y     <= resize(Z(65 downto 32), 66);
            er    <= er - ed + 38;
            R     <= (others => '0');
            cnt   <= to_unsigned(28, 8);
            cont  <= C_ROUND;
            state <= F_DIV;

          -------------------------------------------------------------------
          -- normalise and round R * 2^(er - 65)
          -------------------------------------------------------------------
          when F_NORM =>
            if cont /= C_ROUND then
              if R(65) = '0' and R /= 0 then
                R  <= R(64 downto 0) & '0';
                er <= er - 1;
              elsif cont = C_TAN1 then
                state <= F_TAN1;
              else
                state <= F_TAN2;
              end if;
            elsif R = 0 then
              state <= F_ROUND;
            elsif er < -126 then
              R   <= '0' & R(65 downto 1);
              stk <= stk or R(0);
              er  <= er + 1;
            elsif R(65) = '0' and er > -126 then
              R  <= R(64 downto 0) & '0';
              er <= er - 1;
            else
              state <= F_ROUND;
            end if;

          when F_ROUND =>
            sticky := stk;
            if R(40 downto 0) /= 0 then
              sticky := '1';
            end if;
            inc  := R(41) and (sticky or R(42));
            mant := '0' & R(65 downto 42);
            if inc = '1' then
              mant := mant + 1;
            end if;
            e2   := er;
            if mant(24) = '1' then
              mant := '0' & mant(24 downto 1);
              e2   := er + 1;
            end if;
            if R = 0 and stk = '0' then
              res_r <= sr & "0000000000000000000000000000000";
            elsif mant(23) = '0' then
              res_r <= sr & "00000000" & std_logic_vector(mant(22 downto 0));
            elsif e2 > 127 then
              res_r <= sr & "1111111100000000000000000000000";
            else
              res_r <= sr & std_logic_vector(to_unsigned(e2 + 127, 8)) & std_logic_vector(mant(22 downto 0));
            end if;
            state <= F_DONE;

          when F_DONE =>
            done_r <= '1';
            state  <= F_IDLE;
        end case;
      end if;
    end if;
  end process;
end architecture;

-------------------------------------------------------------------------------

-- SPI master for the Tiny Tapeout QSPI Pmod (two APS6404L PSRAMs), plain SPI mode 0.
-- Reads use command 0x03, writes 0x02, both with a 24-bit address and no dummy cycles.
-- SCK runs at clk/2. Data is little endian: the byte at addr goes into bits 7..0.
-- addr(23) picks the chip: 0 -> RAM A (cs_n(0)), 1 -> RAM B (cs_n(1)), giving 16 MiB.
-- addr, we, size and wdata must stay stable from req until done.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity cupu_spi is
  port (
    clk   : in  std_logic;
    rst   : in  std_logic;
    req   : in  std_logic;
    we    : in  std_logic;
    size  : in  std_logic_vector(1 downto 0);  -- 00 byte, 01 half, 10 word
    addr  : in  std_logic_vector(23 downto 0);
    wdata : in  std_logic_vector(31 downto 0);
    rdata : out std_logic_vector(31 downto 0);
    done  : out std_logic;                     -- one-cycle pulse, rdata valid with it
    sck   : out std_logic;
    mosi  : out std_logic;
    miso  : in  std_logic;
    cs_n  : out std_logic_vector(1 downto 0)
  );
end entity;

architecture rtl of cupu_spi is
  type state_t is (S_IDLE, S_XFER, S_GAP);
  signal state  : state_t;
  signal sreg   : std_logic_vector(31 downto 0);
  signal bitcnt : unsigned(5 downto 0);
  signal sck_r  : std_logic;
  signal cs_r   : std_logic_vector(1 downto 0);
  signal gap    : unsigned(1 downto 0);
  signal last   : unsigned(5 downto 0);
begin
  sck  <= sck_r;
  mosi <= sreg(31);
  cs_n <= cs_r;

  -- index of the final bit: 32 command/address bits + 8, 16 or 32 data bits
  with size select last <=
    to_unsigned(39, 6) when "00",
    to_unsigned(47, 6) when "01",
    to_unsigned(63, 6) when others;

  process (clk)
    variable sh : std_logic_vector(31 downto 0);
  begin
    if rising_edge(clk) then
      done <= '0';
      if rst = '1' then
        state <= S_IDLE;
        sck_r <= '0';
        cs_r  <= "11";
        rdata <= (others => '0');
      else
        case state is
          when S_IDLE =>
            if req = '1' then
              if we = '1' then
                sreg <= x"02" & addr;
              else
                sreg <= x"03" & addr;
              end if;
              cs_r   <= (not addr(23)) & addr(23);
              bitcnt <= (others => '0');
              state  <= S_XFER;
            end if;

          when S_XFER =>
            if sck_r = '0' then
              sck_r <= '1';
            else
              -- falling edge: sample MISO late for pad-delay margin, shift out next bit
              sck_r <= '0';
              sh := sreg(30 downto 0) & miso;
              if bitcnt = last then
                case size is
                  when "00"   => rdata <= x"000000" & sh(7 downto 0);
                  when "01"   => rdata <= x"0000" & sh(7 downto 0) & sh(15 downto 8);
                  when others => rdata <= sh(7 downto 0) & sh(15 downto 8) & sh(23 downto 16) & sh(31 downto 24);
                end case;
                cs_r  <= "11";
                done  <= '1';
                gap   <= (others => '1');
                state <= S_GAP;
              else
                if bitcnt = 31 and we = '1' then
                  sreg <= wdata(7 downto 0) & wdata(15 downto 8) & wdata(23 downto 16) & wdata(31 downto 24);
                else
                  sreg <= sh;
                end if;
                bitcnt <= bitcnt + 1;
              end if;
            end if;

          when S_GAP =>
            -- keep CS high for a few cycles (PSRAM tCPH) and drop the requester's stale req
            if gap = 0 then
              state <= S_IDLE;
            else
              gap <= gap - 1;
            end if;
        end case;
      end if;
    end if;
  end process;
end architecture;

-------------------------------------------------------------------------------

-- CUPU-II "Stollentroll" core, multi-cycle implementation of isa.txt.
--
-- Everything shares one 33-bit adder and one register-file read port; mul/div are
-- iterative (32 cycles) and shifts go one bit per cycle. Fetches over SPI take ~130
-- cycles anyway, so the extra cycles are cheap and the area savings are not.
-- Floating point ops (func 0x0E..0x17) run in cupu_fpu.
--
-- Differences from the Go emulator are listed in docs/info.md.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity cupu_core is
  generic (
    G_CLK_HZ : natural := 25_000_000  -- for the seconds counter at 0x20000000
  );
  port (
    clk       : in  std_logic;
    rst       : in  std_logic;
    -- external memory (addresses below 0x01000000)
    mem_req   : out std_logic;
    mem_we    : out std_logic;
    mem_size  : out std_logic_vector(1 downto 0);
    mem_addr  : out std_logic_vector(23 downto 0);
    mem_wdata : out std_logic_vector(31 downto 0);
    mem_rdata : in  std_logic_vector(31 downto 0);
    mem_done  : in  std_logic;
    -- mmio
    kbd_in    : in  std_logic_vector(7 downto 0);
    gpio_out  : out std_logic_vector(7 downto 0)
  );
end entity;

architecture rtl of cupu_core is
  subtype word is unsigned(31 downto 0);
  type regfile_t is array (0 to 31) of word;  -- entry 0 is never written

  type state_t is (
    S_FETCH, S_RA, S_RB, S_EXEC, S_MEM, S_WB, S_WBJ, S_NEXT, S_JRAL,
    S_MUL, S_DIV_NA, S_DIV_NB, S_DIV, S_DIV_FQ, S_DIV_FR, S_SHIFT, S_FPU,
    S_CLEAR, S_HALT
  );

  type op_t is (
    OP_NOP, OP_ADD, OP_SUB, OP_MUL, OP_MHI, OP_DIV, OP_DIVU, OP_REM,
    OP_OR, OP_AND, OP_XOR, OP_NOT, OP_SHL, OP_SHR, OP_OVRF, OP_UNRF, OP_FPU,
    OP_CMP, OP_LOAD, OP_STORE, OP_HLT, OP_LUI, OP_JAL, OP_JRAL
  );

  constant MMIO_BASE : unsigned(27 downto 0) := x"2000000";  -- addr(31 downto 4)

  signal regs  : regfile_t;
  signal state : state_t;
  signal pc, ir, opa, opb, acc : word;
  signal cnt   : unsigned(4 downto 0);
  signal flag, sgn_q, sgn_r    : std_logic;

  -- instruction fields
  signal f_cond : std_logic;
  signal f_opc  : unsigned(4 downto 0);
  signal f_t, f_a, f_b : unsigned(4 downto 0);
  signal f_fn   : unsigned(10 downto 0);
  signal op     : op_t;

  signal rf_idx : unsigned(4 downto 0);
  signal rf_rd  : word;
  signal wb_val : word;
  signal pc_inc : word;

  -- shared adder: add_s = x + (y xor inv) + cin, 34 bits so bit 33 is the carry
  signal add_x, add_y : unsigned(32 downto 0);
  signal add_inv, add_cin : std_logic;
  signal add_s : unsigned(33 downto 0);

  -- memory access
  signal acc_addr  : word;
  signal acc_size  : std_logic_vector(1 downto 0);
  signal acc_req   : std_logic;
  signal mmio_sel  : std_logic;
  signal mmio_rd   : word;
  signal acc_done  : std_logic;
  signal acc_rdata : word;

  -- fpu
  signal fpu_start : std_logic;
  signal fpu_op    : unsigned(4 downto 0);
  signal fpu_res   : std_logic_vector(31 downto 0);
  signal fpu_done  : std_logic;

  -- mmio devices
  signal gpio      : std_logic_vector(7 downto 0);
  signal seconds   : word;
  signal ts_we     : std_logic;
  signal kbd_sync  : std_logic_vector(2 downto 0);
  signal kbd_data  : std_logic_vector(6 downto 0);
  signal kbd_valid : std_logic;
  signal kbd_hit   : std_logic;  -- current load reads the keyboard byte
  signal kbd_take  : std_logic;
  signal prescale  : natural range 0 to G_CLK_HZ - 1;
begin
  f_cond <= ir(31);
  f_opc  <= ir(30 downto 26);
  f_t    <= ir(25 downto 21);
  f_a    <= ir(20 downto 16);
  f_b    <= ir(15 downto 11);
  f_fn   <= ir(10 downto 0);

  ---------------------------------------------------------------------------
  -- decode
  ---------------------------------------------------------------------------
  process (f_opc, f_fn)
  begin
    op <= OP_NOP;
    if f_opc = 0 then
      case to_integer(f_fn) is
        when 16#00# => op <= OP_ADD;
        when 16#01# => op <= OP_SUB;
        when 16#02# => op <= OP_MUL;
        when 16#03# => op <= OP_DIV;
        when 16#04# => op <= OP_OR;
        when 16#05# => op <= OP_AND;
        when 16#06# => op <= OP_XOR;
        when 16#07# => op <= OP_NOT;
        when 16#08# => op <= OP_SHL;
        when 16#09# => op <= OP_SHR;
        when 16#0A# => op <= OP_REM;
        when 16#0B# => op <= OP_MHI;
        when 16#0C# => op <= OP_OVRF;
        when 16#0D# => op <= OP_UNRF;
        when 16#0E# to 16#17# => op <= OP_FPU;
        when 16#20# to 16#25# => op <= OP_CMP;
        when 16#30# to 16#32# => op <= OP_LOAD;
        when 16#33# to 16#35# => op <= OP_STORE;
        when 16#40# => op <= OP_HLT;
        when others => null;
      end case;
    else
      case to_integer(f_opc) is
        when 16#08# | 16#18# => op <= OP_ADD;
        when 16#09# | 16#19# => op <= OP_SUB;
        when 16#0A# | 16#1A# => op <= OP_MUL;
        when 16#0B#          => op <= OP_DIV;
        when 16#1B#          => op <= OP_DIVU;
        when 16#0C# | 16#1C# => op <= OP_OR;
        when 16#0D# | 16#1D# => op <= OP_AND;
        when 16#0E# | 16#1E# => op <= OP_XOR;
        when 16#0F#          => op <= OP_LUI;
        when 16#10#          => op <= OP_JAL;
        when 16#11#          => op <= OP_JRAL;
        when others => null;
      end case;
    end if;
  end process;

  ---------------------------------------------------------------------------
  -- register file (one read port, $0 reads as zero and is never written)
  ---------------------------------------------------------------------------
  rf_idx <= f_a when state = S_RA else
            f_t when op = OP_STORE else
            f_b;
  process (rf_idx, regs)
  begin
    rf_rd <= (others => '0');
    if rf_idx /= 0 then
      rf_rd <= regs(to_integer(rf_idx));
    end if;
  end process;

  -- mul, div and udivi leave their result in opa; everything else in acc
  wb_val <= opa when op = OP_MUL or op = OP_DIV or op = OP_DIVU else acc;

  pc_inc <= pc + 4;

  ---------------------------------------------------------------------------
  -- shared adder
  ---------------------------------------------------------------------------
  process (state, op, opa, opb, acc, pc, cnt)
  begin
    add_x   <= '0' & opa;
    add_y   <= '0' & opb;
    add_inv <= '0';
    add_cin <= '0';
    case state is
      when S_EXEC =>
        case op is
          when OP_SUB | OP_UNRF | OP_CMP =>
            add_inv <= '1';
            add_cin <= '1';
          when OP_OVRF =>
            add_cin <= '1';
          when others => null;
        end case;
      when S_JRAL =>
        add_x <= '0' & pc;
        add_y <= '0' & opa;
      when S_MUL =>
        -- signed shift-add; the multiplier's sign bit has negative weight
        add_x <= acc(31) & acc;
        if opa(0) = '1' then
          add_y <= opb(31) & opb;
          if cnt = 31 then
            add_inv <= '1';
            add_cin <= '1';
          end if;
        else
          add_y <= (others => '0');
        end if;
      when S_DIV_NA | S_DIV_FQ =>
        add_x   <= (others => '0');
        add_y   <= '0' & opa;
        add_inv <= '1';
        add_cin <= '1';
      when S_DIV_NB =>
        add_x   <= (others => '0');
        add_y   <= '0' & opb;
        add_inv <= '1';
        add_cin <= '1';
      when S_DIV =>
        add_x   <= acc & opa(31);
        add_y   <= '0' & opb;
        add_inv <= '1';
        add_cin <= '1';
      when S_DIV_FR =>
        add_x   <= (others => '0');
        add_y   <= '0' & acc;
        add_inv <= '1';
        add_cin <= '1';
      when others => null;
    end case;
  end process;

  process (add_x, add_y, add_inv, add_cin)
    variable y : unsigned(32 downto 0);
    variable c : unsigned(33 downto 0);
  begin
    y := add_y;
    if add_inv = '1' then
      y := not add_y;
    end if;
    c := (0 => add_cin, others => '0');
    add_s <= ('0' & add_x) + ('0' & y) + c;
  end process;

  ---------------------------------------------------------------------------
  -- floating point
  ---------------------------------------------------------------------------
  fpu_op <= f_fn(4 downto 0) - 16#0E#;

  u_fpu : entity work.cupu_fpu
    port map (
      clk   => clk,
      rst   => rst,
      start => fpu_start,
      op    => fpu_op(3 downto 0),
      a     => std_logic_vector(opa),
      b     => std_logic_vector(opb),
      res   => fpu_res,
      done  => fpu_done
    );

  ---------------------------------------------------------------------------
  -- memory access: external SPI RAM below 0x01000000, mmio above
  ---------------------------------------------------------------------------
  acc_addr <= pc when state = S_FETCH else opa;
  acc_req  <= '1' when state = S_FETCH or state = S_MEM else '0';
  process (state, f_fn)
  begin
    if state = S_FETCH then
      acc_size <= "10";
    else
      case f_fn(2 downto 0) is
        when "000" | "011" => acc_size <= "10";  -- lw / sw
        when "001" | "100" => acc_size <= "01";  -- lh / sh
        when others        => acc_size <= "00";  -- lb / sb
      end case;
    end if;
  end process;

  mmio_sel  <= '0' when acc_addr(31 downto 24) = 0 else '1';
  mem_req   <= acc_req and not mmio_sel;
  mem_we    <= '1' when state = S_MEM and op = OP_STORE else '0';
  mem_size  <= acc_size;
  mem_addr  <= std_logic_vector(acc_addr(23 downto 0));
  mem_wdata <= std_logic_vector(opb);
  -- a load of the keyboard byte blocks until a key is there, like the emulator's channel
  acc_done  <= mem_done when mmio_sel = '0' else not (kbd_hit and not kbd_valid);
  kbd_take  <= '1' when state = S_MEM and op = OP_LOAD and kbd_hit = '1' and kbd_valid = '1' else '0';

  process (acc_addr, acc_size, state, op)
    variable off, n : natural;
  begin
    off := to_integer(acc_addr(3 downto 0));
    case acc_size is
      when "00"   => n := 1;
      when "01"   => n := 2;
      when others => n := 4;
    end case;
    kbd_hit <= '0';
    if acc_addr(31 downto 4) = MMIO_BASE and off <= 4 and off + n > 4
       and not (state = S_MEM and op = OP_STORE) then
      kbd_hit <= '1';
    end if;
  end process;

  -- mmio is read byte by byte like the emulator, so unaligned accesses behave the same
  process (acc_addr, acc_size, seconds, kbd_data, gpio)
    variable off : unsigned(4 downto 0);
    variable b   : std_logic_vector(7 downto 0);
    variable r   : std_logic_vector(31 downto 0);
  begin
    r := (others => '0');
    for k in 0 to 3 loop
      off := ('0' & acc_addr(3 downto 0)) + k;
      b   := (others => '0');
      if acc_addr(31 downto 4) = MMIO_BASE then
        case to_integer(off) is
          when 0      => b := std_logic_vector(seconds(7 downto 0));
          when 1      => b := std_logic_vector(seconds(15 downto 8));
          when 2      => b := std_logic_vector(seconds(23 downto 16));
          when 3      => b := std_logic_vector(seconds(31 downto 24));
          when 4      => b := '0' & kbd_data;
          when 8      => b := gpio;
          when others => null;
        end case;
      end if;
      r(8 * k + 7 downto 8 * k) := b;
    end loop;
    case acc_size is
      when "00"   => r(31 downto 8) := (others => '0');
      when "01"   => r(31 downto 16) := (others => '0');
      when others => null;
    end case;
    mmio_rd <= unsigned(r);
  end process;

  acc_rdata <= unsigned(mem_rdata) when mmio_sel = '0' else mmio_rd;

  gpio_out <= gpio;

  ---------------------------------------------------------------------------
  -- seconds counter: counts from reset; a word store to 0x20000000 sets it
  -- (e.g. to unix time, which is what the emulator returns)
  ---------------------------------------------------------------------------
  ts_we <= '1' when state = S_MEM and op = OP_STORE and acc_addr = x"20000000" and acc_size = "10" else '0';

  process (clk)
  begin
    if rising_edge(clk) then
      if rst = '1' then
        prescale <= 0;
        seconds  <= (others => '0');
      elsif ts_we = '1' then
        prescale <= 0;
        seconds  <= opb;
      elsif prescale = G_CLK_HZ - 1 then
        prescale <= 0;
        seconds  <= seconds + 1;
      else
        prescale <= prescale + 1;
      end if;
    end if;
  end process;

  ---------------------------------------------------------------------------
  -- keyboard: a rising edge on ui_in(7) latches the 7-bit character on ui_in(6:0)
  ---------------------------------------------------------------------------
  process (clk)
  begin
    if rising_edge(clk) then
      if rst = '1' then
        kbd_sync  <= (others => '0');
        kbd_valid <= '0';
        kbd_data  <= (others => '0');
      else
        kbd_sync <= kbd_sync(1 downto 0) & kbd_in(7);
        if kbd_sync(1) = '1' and kbd_sync(2) = '0' then
          kbd_data  <= kbd_in(6 downto 0);
          kbd_valid <= '1';
        elsif kbd_take = '1' then
          kbd_valid <= '0';
        end if;
      end if;
    end if;
  end process;

  ---------------------------------------------------------------------------
  -- register file write; S_CLEAR zeroes it after reset, one register per cycle
  ---------------------------------------------------------------------------
  process (clk)
  begin
    if rising_edge(clk) then
      if state = S_CLEAR then
        regs(to_integer(cnt)) <= (others => '0');
      elsif (state = S_WB or state = S_WBJ) and f_t /= 0 then
        regs(to_integer(f_t)) <= wb_val;
      end if;
    end if;
  end process;

  ---------------------------------------------------------------------------
  -- control
  ---------------------------------------------------------------------------
  process (clk)
    variable ge, eq : std_logic;
    variable signd  : std_logic;
  begin
    if rising_edge(clk) then
      fpu_start <= '0';
      if rst = '1' then
        state <= S_CLEAR;
        cnt   <= (others => '0');
        pc    <= (others => '0');
        flag  <= '0';
        gpio  <= (others => '0');
      else
        ge    := add_s(33);  -- no borrow from opa - opb
        eq    := '1' when opa = opb else '0';
        signd := '0' when op = OP_DIVU else '1';

        case state is
          when S_FETCH =>
            if acc_done = '1' then
              ir    <= acc_rdata;
              state <= S_RA;
            end if;

          when S_RA =>
            opa   <= rf_rd;
            state <= S_RB;

          when S_RB =>
            if f_opc = 0 then
              opb <= rf_rd;
            elsif f_opc(4 downto 3) = "11" then
              opb <= resize(ir(15 downto 0), 32);                    -- 0x18..0x1E
            else
              opb <= unsigned(resize(signed(ir(15 downto 0)), 32));  -- 0x08..0x11
            end if;
            state <= S_EXEC;

          when S_EXEC =>
            state <= S_WB;
            if f_cond = '1' and flag = '0' then
              state <= S_NEXT;
            else
              case op is
                when OP_ADD | OP_SUB => acc <= add_s(31 downto 0);
                when OP_OR   => acc <= opa or opb;
                when OP_AND  => acc <= opa and opb;
                when OP_XOR  => acc <= opa xor opb;
                when OP_NOT  => acc <= not opa;
                when OP_OVRF => acc <= (0 => add_s(32), others => '0');
                when OP_UNRF => acc <= (0 => (not ge) or eq, others => '0');
                when OP_FPU =>
                  fpu_start <= '1';
                  state     <= S_FPU;
                when OP_LUI  => acc <= opb(15 downto 0) & x"0000";

                when OP_CMP =>
                  case f_fn(2 downto 0) is
                    when "000"  => flag <= eq;
                    when "001"  => flag <= not eq;
                    when "010"  => flag <= ge and not eq;
                    when "011"  => flag <= ge;
                    when "100"  => flag <= not ge;
                    when others => flag <= (not ge) or eq;
                  end case;
                  state <= S_NEXT;

                when OP_MUL | OP_MHI =>
                  acc   <= (others => '0');
                  cnt   <= (others => '0');
                  state <= S_MUL;

                when OP_DIV | OP_DIVU | OP_REM =>
                  if opb = 0 then
                    state <= S_HALT;  -- the emulator panics
                  else
                    state <= S_DIV_NA;
                  end if;

                when OP_SHL | OP_SHR =>
                  if opb(31 downto 5) /= 0 then
                    acc <= (others => '0');
                  else
                    acc   <= opa;
                    cnt   <= opb(4 downto 0);
                    state <= S_SHIFT;
                  end if;

                when OP_LOAD | OP_STORE =>
                  state <= S_MEM;

                when OP_JAL =>
                  acc   <= pc_inc;
                  pc    <= add_s(31 downto 0);
                  state <= S_WBJ;

                when OP_JRAL =>
                  opa   <= add_s(31 downto 0);  -- imm + $a, then pc + that
                  state <= S_JRAL;

                when OP_HLT =>
                  state <= S_HALT;

                when OP_NOP =>
                  state <= S_NEXT;
              end case;
            end if;

          when S_JRAL =>
            acc   <= pc_inc;
            pc    <= add_s(31 downto 0);
            state <= S_WBJ;

          when S_MUL =>
            acc <= add_s(32 downto 1);
            opa <= add_s(0) & opa(31 downto 1);
            cnt <= cnt + 1;
            if cnt = 31 then
              state <= S_WB;
            end if;

          when S_DIV_NA =>
            sgn_q <= signd and (opa(31) xor opb(31));
            sgn_r <= signd and opa(31);
            if signd = '1' and opa(31) = '1' then
              opa <= add_s(31 downto 0);
            end if;
            state <= S_DIV_NB;

          when S_DIV_NB =>
            if signd = '1' and opb(31) = '1' then
              opb <= add_s(31 downto 0);
            end if;
            acc   <= (others => '0');
            cnt   <= (others => '0');
            state <= S_DIV;

          when S_DIV =>
            -- restoring division on magnitudes: quotient shifts into opa, remainder in acc
            if ge = '1' then
              acc <= add_s(31 downto 0);
            else
              acc <= acc(30 downto 0) & opa(31);
            end if;
            opa <= opa(30 downto 0) & ge;
            cnt <= cnt + 1;
            if cnt = 31 then
              state <= S_DIV_FQ;
            end if;

          when S_DIV_FQ =>
            if sgn_q = '1' then
              opa <= add_s(31 downto 0);
            end if;
            state <= S_DIV_FR;

          when S_DIV_FR =>
            if sgn_r = '1' then
              acc <= add_s(31 downto 0);
            end if;
            state <= S_WB;

          when S_SHIFT =>
            if cnt = 0 then
              state <= S_WB;
            else
              if f_fn(0) = '0' then
                acc <= acc(30 downto 0) & '0';
              else
                acc <= '0' & acc(31 downto 1);
              end if;
              cnt <= cnt - 1;
            end if;

          when S_MEM =>
            if acc_done = '1' then
              if op = OP_LOAD then
                acc   <= acc_rdata;
                state <= S_WB;
              else
                if mmio_sel = '1' and opa = x"20000008" then
                  gpio <= std_logic_vector(opb(7 downto 0));
                end if;
                state <= S_NEXT;
              end if;
            end if;

          when S_WB | S_NEXT =>
            pc    <= pc_inc;
            state <= S_FETCH;

          when S_WBJ =>
            state <= S_FETCH;

          when S_FPU =>
            if fpu_done = '1' then
              acc   <= unsigned(fpu_res);
              state <= S_WB;
            end if;

          when S_CLEAR =>
            cnt <= cnt + 1;
            if cnt = 31 then
              state <= S_FETCH;
            end if;

          when S_HALT =>
            null;
        end case;
      end if;
    end if;
  end process;
end architecture;

-------------------------------------------------------------------------------

-- Tiny Tapeout top level for CUPU-II.
--
-- ui_in   : keyboard: a rising edge on ui_in(7) latches the character on ui_in(6:0),
--           read (blocking) at 0x20000004
-- uo_out  : gpio register, written/read at 0x20000008
-- uio     : TT QSPI Pmod in plain SPI mode (CS0 flash held high, CS1 RAM A, CS2 RAM B)
--
-- While rst_n is low every uio pin is an input, so the demo board's RP2040 can
-- preload a program into the PSRAM before releasing reset. Execution starts at 0.

library ieee;
use ieee.std_logic_1164.all;

entity tt_um_zonlykroks_cupu is
  port (
    ui_in   : in  std_logic_vector(7 downto 0);
    uo_out  : out std_logic_vector(7 downto 0);
    uio_in  : in  std_logic_vector(7 downto 0);
    uio_out : out std_logic_vector(7 downto 0);
    uio_oe  : out std_logic_vector(7 downto 0);
    ena     : in  std_logic;
    clk     : in  std_logic;
    rst_n   : in  std_logic
  );
end entity;

architecture rtl of tt_um_zonlykroks_cupu is
  signal rst : std_logic;

  signal mem_req, mem_we, mem_done : std_logic;
  signal mem_size  : std_logic_vector(1 downto 0);
  signal mem_addr  : std_logic_vector(23 downto 0);
  signal mem_wdata : std_logic_vector(31 downto 0);
  signal mem_rdata : std_logic_vector(31 downto 0);

  signal sck, mosi : std_logic;
  signal cs_n      : std_logic_vector(1 downto 0);
begin
  rst <= not rst_n;

  u_core : entity work.cupu_core
    generic map (G_CLK_HZ => 25_000_000)
    port map (
      clk       => clk,
      rst       => rst,
      mem_req   => mem_req,
      mem_we    => mem_we,
      mem_size  => mem_size,
      mem_addr  => mem_addr,
      mem_wdata => mem_wdata,
      mem_rdata => mem_rdata,
      mem_done  => mem_done,
      kbd_in    => ui_in,
      gpio_out  => uo_out
    );

  u_spi : entity work.cupu_spi
    port map (
      clk   => clk,
      rst   => rst,
      req   => mem_req,
      we    => mem_we,
      size  => mem_size,
      addr  => mem_addr,
      wdata => mem_wdata,
      rdata => mem_rdata,
      done  => mem_done,
      sck   => sck,
      mosi  => mosi,
      miso  => uio_in(2),
      cs_n  => cs_n
    );

  uio_out(0) <= '1';      -- flash CS, keep deselected
  uio_out(1) <= mosi;
  uio_out(2) <= '0';      -- MISO (input)
  uio_out(3) <= sck;
  uio_out(4) <= '0';      -- SD2, unused
  uio_out(5) <= '0';      -- SD3, unused
  uio_out(6) <= cs_n(0);  -- RAM A
  uio_out(7) <= cs_n(1);  -- RAM B

  uio_oe <= x"00" when rst_n = '0' else "11001011";
end architecture;

-------------------------------------------------------------------------------

