-- CUPU-II "Stollentroll" for Tiny Tapeout: package, FPU, SPI memory controller,
-- CPU core and the tt_um top level (last, so it is the unit ghdl elaborates).

-- BEGIN cupu_fpu_pkg (generated by gen_fpu_pkg.py)
-- Generated by gen_fpu_pkg.py, do not edit.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package cupu_fpu_pkg is
  constant TWO_OVER_PI : std_logic_vector(0 to 255) := "0101000101111100110000011011011100100111001000100000101010010100111111100001001110101011111010001111101010011010011011101110000001101101101100010100101011001100100111100010000111001000001000001111111100101000101100011101010111101111010111011110001010110000";
  constant PI_HALF     : std_logic_vector(0 to 127) := "11001001000011111101101010100010001000010110100011000010001101001100010011000110011000101000101110000000110111000001110011010001";
  constant CORDIC_K    : unsigned(65 downto 0) := "000010011011011101001110110110101000010000110101111001011010011010";
  constant ATAN_ROM    : std_logic_vector(0 to 4095) :=
    "10110001000011000101101000010001000101010110111111000010010011000000000000000000000000000000000000000000000000000000000000000000" &
    "10010110111100101101110110000110101000001110011000110101101110000000000000000000000000000000000000000000000000000000000000000000" &
    "10001101011101100000001001101001001111110101110110110101111100000000000000000000000000000000000000000000000000000000000000000000" &
    "01001110110110111101000011010101011001010111011010101111111000000000000000000000000000000000000000000000000000000000000000000000" &
    "10011100101111011111100110100111011011101101010101111111110000000000000000000000000000000000000000000000000000000000000000000000" &
    "11010010010001101110100101011101110110101010101111111111100000000000000000000000000000000000000000000000000000000000000000000000" &
    "01101011001010011101101110111011010101010101111111111111000000000000000000000000000000000000000000000000000000000000000000000000" &
    "10111010010101110111011101101010101010101111111111111110000000000000000000000000000000000000000000000000000000000000000000000000" &
    "01110110111011101110110101010101010101111111111111111100000000000000000000000000000000000000000000000000000000000000000000000000" &
    "00111101110111011010101010101010101111111111111111111000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "01111011101101010101010101010101111111111111111111110000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "11110110101010101010101010101111111111111111111111100000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "11010101010101010101010101111111111111111111111111000000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "10101010101010101010101111111111111111111111111110000000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "11010101010101010101111111111111111111111111111100000000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "10101010101010101111111111111111111111111111111000000000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "11010101010101111111111111111111111111111111110000000000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "10101010101111111111111111111111111111111111100000000000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "11010101111111111111111111111111111111111111000000000000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "10101111111111111111111111111111111111111110000000000000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "11111111111111111111111111111111111111111100000000000000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "00000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "00000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "00000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "00000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "00000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "00000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "00000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "00000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "00000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "00000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" &
    "00000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
end package;
-- END cupu_fpu_pkg

-------------------------------------------------------------------------------

-- CUPU-II floating point unit: IEEE 754 binary32, round to nearest even.
--
--   op  func  operation
--   0   0x0E  itof   int32 -> float
--   1   0x0F  ftoi   float -> int32, round half away from zero (Go math.Round);
--                    NaN, inf and out of range give 0x80000000
--   2   0x10  fadd
--   3   0x11  fsub
--   4   0x12  fmul
--   5   0x13  fdiv
--   6   0x14  sqrt
--   7   0x15  sin
--   8   0x16  cos
--   9   0x17  tan
--
-- Bit-serial: one 1-bit adder and 66-bit rotating registers (see the architecture).
-- Results are exact (correctly rounded) for itof/ftoi/fadd/fsub/fmul/fdiv/sqrt,
-- subnormals included. sin/cos/tan use Payne-Hanek argument reduction and a 62-step
-- CORDIC with 62 fraction bits; they are within 1 ulp and almost always correctly
-- rounded. Every NaN result is 0x7FC00000.
--
-- a and b must stay stable from start until done.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.cupu_fpu_pkg.all;

entity cupu_fpu is
  port (
    clk   : in  std_logic;
    rst   : in  std_logic;
    start : in  std_logic;                     -- one-cycle pulse
    op    : in  unsigned(3 downto 0);
    a     : in  std_logic_vector(31 downto 0);
    b     : in  std_logic_vector(31 downto 0);
    res   : out std_logic_vector(31 downto 0);
    done  : out std_logic                      -- one-cycle pulse, res valid with it
  );
end entity;

architecture rtl of cupu_fpu is
  constant OP_ITOF : natural := 0;
  constant OP_FTOI : natural := 1;
  constant OP_FADD : natural := 2;
  constant OP_FSUB : natural := 3;
  constant OP_FMUL : natural := 4;
  constant OP_FDIV : natural := 5;
  constant OP_SQRT : natural := 6;
  constant OP_SIN  : natural := 7;
  constant OP_COS  : natural := 8;
  constant OP_TAN  : natural := 9;

  constant QNAN  : std_logic_vector(31 downto 0) := x"7FC00000";
  constant ONE_F : std_logic_vector(31 downto 0) := x"3F800000";

  -- Bit-serial datapath. R, X, Y and Z are 66-bit rings that rotate one bit per clock,
  -- in step with the phase ph (0..65): bit ph of each one is at position 0, and in
  -- general position k holds bit ph + k. An operation is a 66-cycle pass, LSB first,
  -- through a 1-bit adder, the result going back in at the top of a ring. Right shifts
  -- read a later position (a tap), left shifts by 1-2 go through delay flops, and a
  -- 24-bit serial-parallel multiplier does fmul and the Payne-Hanek product. Results are
  -- not normalised by shifting: the position of R's top bit is tracked and the rounding
  -- pass reads the mantissa window straight out of R.
  --
  -- States marked "pass" last one full revolution (ph 0..65) and move on at ph = 65.
  type state_t is (
    F_IDLE, F_PRENORM, F_SYNC, F_PACK, F_DONE,
    F_ITOF,                                  -- pass: R = |a|
    F_FTOI_LD, F_FTOI_NEG, F_FTOI_RES,       -- pass, pass, one cycle
    F_ADD_LD1, F_ADD_LD2, F_ADD_SUM,         -- passes
    F_MUL,                                   -- pass: R = ma * mb
    F_DIV_LDX, F_DIV_LDY, F_DIV_A, F_DIV_B,  -- passes
    F_SQ_LD, F_SQ_A, F_SQ_B, F_SQ_END,       -- passes
    F_TS_LD,                                 -- pass
    F_PH_WAIT, F_PH,                         -- 94-cycle product starting at ph = 40
    F_PH_ASR, F_PIM, F_TRIG_START,           -- passes
    F_C1, F_C2, F_C3,                        -- passes: one CORDIC iteration
    F_TRIG_OUT, F_TAN_D, F_TAN_N, F_TAN_X, F_TAN_Y,  -- passes
    F_ROUND                                  -- pass: read the mantissa window
  );

  subtype exp_t is integer range -1024 to 1023;

  signal state, nxt : state_t;
  signal opn        : natural range 0 to 15;
  signal ph         : unsigned(6 downto 0);

  signal R, X, Y, Z             : unsigned(65 downto 0);
  signal rdin, xdin, ydin, zdin : std_logic;
  signal r_we, x_we, y_we       : std_logic;
  signal sbit, cout             : std_logic;
  signal carry, ge              : std_logic;
  signal xs, ys, zs             : std_logic;      -- bit 65 of X, Y, Z
  signal rdly, sdly, zdly       : std_logic;      -- R(0), sum and Z(0), one cycle ago
  signal xdly, ydly             : std_logic_vector(1 downto 0);
  signal pmsb, pd               : integer range 0 to 65;
  signal rnz, xnz, ynz          : std_logic;      -- written value non-zero so far
  signal sh                     : unsigned(6 downto 0);  -- right tap for X and Y
  signal lsh                    : integer range -64 to 127; -- left shift R -> Z / X (tan)

  signal ma, mb       : unsigned(23 downto 0);
  signal ea, eb, er   : exp_t;
  signal moff         : integer range -128 to 127;  -- ring bit j <- mantissa bit j + moff
  signal sr, stk      : std_logic;
  signal effsub, swap : std_logic;
  signal asticky      : std_logic;
  signal tiny         : std_logic;
  signal cnt          : unsigned(7 downto 0);
  signal nn, nt       : unsigned(6 downto 0);
  signal quad         : unsigned(1 downto 0);
  signal t66, t67     : std_logic;

  -- serial-parallel multiplier (carry-save, LSB first)
  signal ms, mc       : unsigned(23 downto 0);
  signal msum, mcar   : unsigned(23 downto 0);
  signal pbit         : std_logic;

  -- rounding
  signal mant         : unsigned(23 downto 0);
  signal gbit, sbits  : std_logic;
  signal win          : exp_t;                 -- position of the mantissa window's LSB in R

  signal res_r  : std_logic_vector(31 downto 0);
  signal done_r : std_logic;

  -- unpacked operands
  signal a_exp, b_exp   : unsigned(7 downto 0);
  signal a_m, b_m       : unsigned(23 downto 0);
  signal a_e, b_e       : exp_t;
  signal a_nan, b_nan   : std_logic;
  signal a_inf, b_inf   : std_logic;
  signal a_zero, b_zero : std_logic;
  signal sa, sb, sbe    : std_logic;

  -- which CORDIC output is converted: '1' = Y (sin r), '0' = X (cos r)
  signal is_sin, is_cos, is_tan, in_out, trig_use_y : std_logic;

  function unpack_e(e : unsigned(7 downto 0)) return exp_t is
  begin
    if e = 0 then
      return -126;
    end if;
    return to_integer(e) - 127;
  end function;
begin
  res  <= res_r;
  done <= done_r;
  opn  <= to_integer(op);

  a_exp  <= unsigned(a(30 downto 23));
  b_exp  <= unsigned(b(30 downto 23));
  a_m(23) <= '0' when a_exp = 0 else '1';  -- hidden bit
  b_m(23) <= '0' when b_exp = 0 else '1';
  a_m(22 downto 0) <= unsigned(a(22 downto 0));
  b_m(22 downto 0) <= unsigned(b(22 downto 0));
  a_e    <= unpack_e(a_exp);
  b_e    <= unpack_e(b_exp);
  a_nan  <= '1' when a_exp = 255 and unsigned(a(22 downto 0)) /= 0 else '0';
  b_nan  <= '1' when b_exp = 255 and unsigned(b(22 downto 0)) /= 0 else '0';
  a_inf  <= '1' when a_exp = 255 and unsigned(a(22 downto 0)) = 0 else '0';
  b_inf  <= '1' when b_exp = 255 and unsigned(b(22 downto 0)) = 0 else '0';
  a_zero <= '1' when unsigned(a(30 downto 0)) = 0 else '0';
  b_zero <= '1' when unsigned(b(30 downto 0)) = 0 else '0';
  sa     <= a(31);
  sb     <= b(31);
  sbe    <= b(31) xor '1' when opn = OP_FSUB else b(31);

  is_sin <= '1' when opn = OP_SIN else '0';
  is_cos <= '1' when opn = OP_COS else '0';
  is_tan <= '1' when opn = OP_TAN else '0';
  in_out <= '1' when state = F_TRIG_OUT else '0';
  -- sin: q even Y, odd X; cos: q even X, odd Y
  -- tan: denominator (F_TRIG_OUT) q even X, odd Y; numerator (F_TAN_N) the other one
  trig_use_y <= (is_sin and not quad(0)) or (is_cos and quad(0)) or
                (is_tan and not (in_out xor quad(0)));

  lsh <= 63 - pmsb;

  -- rounding window: the float's LSB is at R position max(msb - 23, -149 - (er - 65))
  win <= pmsb - 23 when pmsb - 23 > -84 - er else -84 - er;

  ---------------------------------------------------------------------------
  -- serial-parallel multiplier: each cycle adds xin * mpar to the carry-save
  -- accumulator and shifts out the product's next bit (pbit)
  ---------------------------------------------------------------------------
  process (state, ph, ma, mb, ms, mc, nn, nt, cnt)
    variable j    : integer range 0 to 127;
    variable xin  : std_logic;
    variable mpar : unsigned(23 downto 0);
    variable pp   : std_logic;
  begin
    j   := to_integer(ph);
    xin := '0';
    if state = F_MUL then
      mpar := mb;
      if j < 24 then
        xin := ma(j);
      end if;
    else
      mpar := ma;
      if nn < nt then
        xin := TWO_OVER_PI(to_integer(cnt));
      end if;
    end if;
    for i in 0 to 23 loop
      pp      := xin and mpar(i);
      msum(i) <= ms(i) xor mc(i) xor pp;
      mcar(i) <= (ms(i) and mc(i)) or (ms(i) and pp) or (mc(i) and pp);
    end loop;
  end process;
  pbit <= msum(0);

  ---------------------------------------------------------------------------
  -- one serial step: adder inputs, the adder, and what goes back into each ring
  ---------------------------------------------------------------------------
  process (state, ph, R, X, Y, Z, carry, ge, xs, ys, zs, rdly, sdly, zdly, xdly, ydly,
           ma, mb, a, moff, swap, effsub, stk, asticky, sa, cnt, tiny, sh, lsh,
           trig_use_y, pbit, nn)
    variable j        : integer range 0 to 127;
    variable m        : unsigned(23 downto 0);
    variable idx      : integer range -256 to 255;
    variable msrc     : std_logic;
    variable av, bv   : std_logic;
    variable iv, cv   : std_logic;
    variable bb, ci   : std_logic;
    variable s        : std_logic;
    variable tapx     : std_logic;
    variable tapy     : std_logic;
    variable tapr     : std_logic;
    variable atan_bit : std_logic;
    variable tz       : std_logic;
    variable rd, xd, yd, zd : std_logic;
    variable rw, xw, yw     : std_logic;
  begin
    j := to_integer(ph);

    -- mantissa bit j + moff (zero outside the mantissa)
    if (state = F_ADD_LD1 and swap = '1') or (state = F_ADD_LD2 and swap = '0') or
       state = F_DIV_LDY then
      m := mb;
    else
      m := ma;
    end if;
    idx  := j + moff;
    msrc := '0';
    if idx >= 0 and idx <= 23 then
      msrc := m(idx);
    end if;

    -- right taps with sign fill, left tap of R
    tapx := xs;
    if j + to_integer(sh) <= 65 then
      tapx := X(to_integer(sh));
    end if;
    tapy := ys;
    if j + to_integer(sh) <= 65 then
      tapy := Y(to_integer(sh));
    end if;
    tapr := '0';
    if lsh <= 0 then
      tapr := R(0);                            -- only used with the top bit at 62 or below
    elsif j >= lsh and lsh <= 65 then
      tapr := R(66 - lsh);
    end if;

    -- atan(2^-i) in Q3.62; past i = 20 it is exactly 2^-i
    if cnt <= 20 then
      atan_bit := ATAN_ROM(to_integer(cnt(4 downto 0) & ph));
    elsif j = 62 - to_integer(cnt(5 downto 0)) then
      atan_bit := '1';
    else
      atan_bit := '0';
    end if;

    -- tiny reduced angle (|r| < 2^-20): decided on Z at ph = 0, remembered after
    if j = 0 then
      if Z(65 downto 42) = 0 or not Z(65 downto 42) = 0 then tz := '1'; else tz := '0'; end if;
    else
      tz := tiny;
    end if;

    -- adder inputs: A + (B xor inv) + cin
    av := '0';
    bv := '0';
    iv := '0';
    case state is
      when F_ITOF =>
        if j < 32 then bv := a(j); else bv := a(31); end if;
        iv := a(31);
      when F_FTOI_LD | F_ADD_LD1 | F_DIV_LDX | F_DIV_LDY | F_SQ_LD | F_TS_LD =>
        av := msrc;
      when F_ADD_LD2 =>
        av := msrc;
        if j = 0 then
          av := msrc or asticky;               -- bits aligned away, folded into bit 0
        end if;
      when F_FTOI_NEG =>
        bv := X(0);
        iv := sa;
      when F_ADD_SUM =>
        av := R(0);
        bv := X(0);
        iv := effsub;
      when F_DIV_A =>
        av := X(0);
        bv := Y(0);
        iv := '1';
      when F_DIV_B =>
        av := X(0);
        bv := Y(0) and ge;
        iv := ge;
      when F_SQ_A | F_SQ_B =>
        -- remainder * 4 + the next two radicand bits (X bits 54, 55) against 4 * root + 1
        if j < 2 then av := X(54); else av := ydly(1); end if;
        if j = 0 then bv := '1'; else bv := Z(0); end if;
        iv := '1';
        if state = F_SQ_B then
          bv := bv and ge;
          iv := ge;
        end if;
      when F_PH_ASR =>
        av := tapx;                            -- X >>> 4
      when F_PIM =>
        if j <= 64 then av := Z(1); else av := zs; end if;  -- Z >>> 1
        if PI_HALF(to_integer(cnt(6 downto 0))) = '1' then
          bv := X(0);
        end if;
      -- CORDIC, rotating towards z = 0:
      --   z >= 0: x -= y>>i, y += x>>i, z -= atan(2^-i)
      --   z <  0: x += y>>i, y -= x>>i, z += atan(2^-i)
      when F_C1 =>
        av := X(0);
        bv := tapy;
        iv := not zs;
      when F_C2 =>
        av := Y(0);
        bv := tapx;
        iv := zs;
      when F_C3 =>
        av := Z(0);
        bv := atan_bit;
        iv := not zs;
      when F_TRIG_OUT | F_TAN_N =>             -- |x| or |y|
        if trig_use_y = '1' then
          bv := Y(0);
          iv := ys;
        else
          bv := X(0);
          iv := xs;
        end if;
      when others => null;
    end case;

    cv := iv;
    if state = F_FTOI_LD then
      cv := stk;                               -- the 0.5 bit rounds away from zero
    end if;
    bb := bv xor iv;
    if j = 0 then ci := cv; else ci := carry; end if;
    s    := av xor bb xor ci;
    cout <= (av and bb) or (av and ci) or (bb and ci);
    sbit <= s;

    -- what goes back into each ring (default: its own bit, i.e. unchanged)
    rd := R(0);
    xd := X(0);
    yd := Y(0);
    zd := Z(0);
    rw := '0';
    xw := '0';
    yw := '0';
    case state is
      when F_ITOF | F_ADD_LD1 | F_ADD_SUM | F_C1 | F_TRIG_OUT | F_TAN_N =>
        rd := s;
        rw := '1';
      when F_FTOI_LD | F_FTOI_NEG | F_ADD_LD2 | F_DIV_LDX =>
        xd := s;
        xw := '1';
      when F_MUL =>
        if j <= 47 then rd := pbit; else rd := '0'; end if;
        rw := '1';
      when F_DIV_LDY =>
        yd := s;
        rd := '0';
        rw := '1';
      when F_DIV_B =>                          -- X = 2 * (X - ge * Y), R = 2 * R + ge
        if j = 0 then xd := '0'; rd := ge; else xd := sdly; rd := rdly; end if;
        xw := '1';
        rw := '1';
      when F_SQ_LD =>
        xd := s;
        yd := '0';
        zd := '0';
      when F_SQ_B =>                           -- Y = remainder, X <<= 2, Z = 4 * (2 root + ge)
        yd := s;
        yw := '1';
        if j < 2 then xd := '0'; else xd := xdly(1); end if;
        if j = 0 then
          zd := '0';
        elsif j = 2 then
          zd := ge;
        else
          zd := zdly;
        end if;
      when F_SQ_END =>
        rd := Z(0);
        rw := '1';
      when F_TS_LD | F_PIM =>
        zd := s;
      when F_PH =>
        if nn >= 26 and nn <= 91 then
          xd := pbit;
        end if;
      when F_PH_ASR =>
        xd := s;
        zd := '0';
      when F_TRIG_START =>
        if tz = '1' then
          if j = 62 then xd := '1'; else xd := '0'; end if;   -- cos r = 1
          yd := Z(0);                                          -- sin r = r
        else
          xd := CORDIC_K(j);
          yd := '0';
        end if;
      when F_C2 =>
        yd := s;
      when F_C3 =>
        xd := R(0);
        zd := s;
      when F_TAN_D =>
        zd := tapr;                            -- denominator, top bit to 63
      when F_TAN_X =>
        xd := tapr;                            -- numerator, top bit to 63
      when F_TAN_Y =>
        yd := Z(0);
        rd := '0';
        rw := '1';
      when others => null;
    end case;
    rdin <= rd;
    xdin <= xd;
    ydin <= yd;
    zdin <= zd;
    r_we <= rw;
    x_we <= xw;
    y_we <= yw;
  end process;

  ---------------------------------------------------------------------------
  -- registers and control
  ---------------------------------------------------------------------------
  process (clk)
    variable big_is_a : boolean;
    variable d        : exp_t;
    variable t        : exp_t;
    variable j        : integer range 0 to 127;
    variable rel      : integer range -2048 to 2047;
    variable m2       : unsigned(24 downto 0);
    variable inc      : std_logic;
    variable sticky   : std_logic;
    variable e2       : exp_t;
    variable v        : std_logic;
    variable nsign    : std_logic;
    variable dsign    : std_logic;
    variable msmall   : unsigned(23 downto 0);
    variable last     : boolean;
  begin
    if rising_edge(clk) then
      j    := to_integer(ph);
      last := ph = 65;
      done_r <= '0';

      -- the rings and the serial bookkeeping run all the time
      if last then ph <= (others => '0'); else ph <= ph + 1; end if;
      R <= rdin & R(65 downto 1);
      X <= xdin & X(65 downto 1);
      Y <= ydin & Y(65 downto 1);
      Z <= zdin & Z(65 downto 1);
      carry <= cout;
      rdly  <= R(0);
      sdly  <= sbit;
      zdly  <= Z(0);
      xdly  <= xdly(0) & X(0);
      ydly  <= ydly(0) & Y(0);
      if last then
        xs <= xdin;
        ys <= ydin;
        zs <= zdin;
        ge <= cout;
      end if;
      if r_we = '1' then
        if j = 0 then
          rnz  <= rdin;
          pmsb <= 0;
        elsif rdin = '1' then
          rnz  <= '1';
          pmsb <= j;
        end if;
      end if;
      if x_we = '1' then
        if j = 0 then xnz <= xdin; elsif xdin = '1' then xnz <= '1'; end if;
      end if;
      if y_we = '1' then
        if j = 0 then ynz <= ydin; elsif ydin = '1' then ynz <= '1'; end if;
      end if;

      if state = F_MUL or state = F_PH then
        ms <= '0' & msum(23 downto 1);
        mc <= mcar;
      else
        ms <= (others => '0');
        mc <= (others => '0');
      end if;

      if state = F_ROUND then
        rel := j - win;
        if rel >= 0 and rel <= 23 then
          mant(rel) <= R(0);
        elsif rel = -1 then
          gbit <= R(0);
        elsif rel < -1 then
          sbits <= sbits or R(0);
        end if;
      elsif state /= F_PACK then
        mant  <= (others => '0');
        gbit  <= '0';
        sbits <= '0';
      end if;

      if rst = '1' then
        state <= F_IDLE;
        ph    <= (others => '0');
        -- not needed by the logic (each op sets what it reads), but without it gate-level
        -- simulation never resolves the X these start with: e.g. nn's clear in F_PH_WAIT
        -- maps to not(nn0) and nn0, which a simulator cannot reduce to 0
        nn      <= (others => '0');
        nt      <= (others => '0');
        cnt     <= (others => '0');
        quad    <= "00";
        sh      <= (others => '0');
        t66     <= '0';
        t67     <= '0';
        tiny    <= '0';
        pd      <= 0;
        stk     <= '0';
        sr      <= '0';
        swap    <= '0';
        effsub  <= '0';
        asticky <= '0';
        nxt     <= F_IDLE;
        moff    <= 0;
        er      <= 0;
      else
        case state is
          -------------------------------------------------------------------
          when F_IDLE =>
            stk  <= '0';
            ma   <= a_m;
            mb   <= b_m;
            ea   <= a_e;
            eb   <= b_e;
            if start = '1' then
              state <= F_DONE;  -- default for the special cases below
              case opn is
                when OP_ITOF =>
                  if a = x"00000000" then
                    res_r <= (others => '0');
                  else
                    sr    <= a(31);
                    er    <= 65;
                    nxt   <= F_ITOF;
                    state <= F_SYNC;
                  end if;

                when OP_FTOI =>
                  if a_exp >= 158 then            -- |a| >= 2^31, inf, NaN
                    res_r <= x"80000000";
                  elsif a_exp < 126 then          -- |a| < 0.5
                    res_r <= (others => '0');
                  else
                    -- integer = m >> (150 - exp); the bit below it rounds half away from zero
                    moff <= 150 - to_integer(a_exp);
                    if a_exp <= 149 then
                      stk <= a_m(149 - to_integer(a_exp));
                    end if;
                    nxt   <= F_FTOI_LD;
                    state <= F_SYNC;
                  end if;

                when OP_FADD | OP_FSUB =>
                  if a_nan = '1' or b_nan = '1' or (a_inf = '1' and b_inf = '1' and sa /= sbe) then
                    res_r <= QNAN;
                  elsif a_inf = '1' then
                    res_r <= sa & a(30 downto 0);
                  elsif b_inf = '1' then
                    res_r <= sbe & b(30 downto 0);
                  else
                    big_is_a := unsigned(a(30 downto 0)) >= unsigned(b(30 downto 0));
                    if big_is_a then
                      swap   <= '0';
                      er     <= a_e + 1;
                      sr     <= sa;
                      d      := a_e - b_e;
                      msmall := b_m;
                    else
                      swap   <= '1';
                      er     <= b_e + 1;
                      sr     <= sbe;
                      d      := b_e - a_e;
                      msmall := a_m;
                    end if;
                    if d > 50 then
                      d := 50;
                    end if;
                    -- mantissas go to bits 64..41; the smaller one shifted right by d with
                    -- everything shifted out folded into bit 0
                    v := '0';
                    for i in 0 to 23 loop
                      if i < d - 41 then
                        v := v or msmall(i);
                      end if;
                    end loop;
                    asticky <= v;
                    cnt     <= to_unsigned(d, 8);
                    moff    <= -41;
                    effsub  <= sa xor sbe;
                    nxt     <= F_ADD_LD1;
                    state   <= F_SYNC;
                  end if;

                when OP_FMUL =>
                  sr <= sa xor sb;
                  if a_nan = '1' or b_nan = '1' or (a_inf = '1' and b_zero = '1') or (a_zero = '1' and b_inf = '1') then
                    res_r <= QNAN;
                  elsif a_inf = '1' or b_inf = '1' then
                    res_r <= (sa xor sb) & "1111111100000000000000000000000";
                  elsif a_zero = '1' or b_zero = '1' then
                    res_r <= (sa xor sb) & "0000000000000000000000000000000";
                  else
                    state <= F_PRENORM;
                  end if;

                when OP_FDIV =>
                  sr <= sa xor sb;
                  if a_nan = '1' or b_nan = '1' or (a_inf = '1' and b_inf = '1') or (a_zero = '1' and b_zero = '1') then
                    res_r <= QNAN;
                  elsif a_inf = '1' or b_zero = '1' then
                    res_r <= (sa xor sb) & "1111111100000000000000000000000";
                  elsif a_zero = '1' or b_inf = '1' then
                    res_r <= (sa xor sb) & "0000000000000000000000000000000";
                  else
                    state <= F_PRENORM;
                  end if;

                when OP_SQRT =>
                  sr <= '0';
                  mb <= x"800000";
                  if a_nan = '1' or (sa = '1' and a_zero = '0') then
                    res_r <= QNAN;
                  elsif a_zero = '1' or a_inf = '1' then
                    res_r <= a;
                  else
                    state <= F_PRENORM;
                  end if;

                when OP_SIN | OP_COS | OP_TAN =>
                  if a_nan = '1' or a_inf = '1' then
                    res_r <= QNAN;
                  elsif a_exp < 115 then          -- |a| < 2^-12
                    if opn = OP_COS then
                      res_r <= ONE_F;
                    else
                      res_r <= a;
                    end if;
                  elsif a_exp < 126 then          -- |a| < 0.5: no reduction needed
                    moff  <= 88 - to_integer(a_exp);  -- Q3.62: m * 2^(exp - 150 + 62)
                    quad  <= "00";
                    nxt   <= F_TS_LD;
                    state <= F_SYNC;
                  else
                    -- Payne-Hanek: stream the bits of 2/pi from the highest one that
                    -- matters (k1) down to the lowest (k0) into the multiplier
                    cnt <= a_exp - 58;                 -- k1
                    if a_exp >= 152 then
                      nt <= to_unsigned(94, 7);        -- k1 - k0 + 1, k0 = exp - 151
                    else
                      nt <= resize(a_exp - 58, 7);     -- k0 = 1
                    end if;
                    state <= F_PH_WAIT;
                  end if;

                when others =>
                  res_r <= QNAN;
              end case;
            end if;

          -------------------------------------------------------------------
          when F_PRENORM =>
            -- make subnormal mantissas start with 1
            if ma(23) = '0' then
              ma <= ma(22 downto 0) & '0';
              ea <= ea - 1;
            elsif mb(23) = '0' then
              mb <= mb(22 downto 0) & '0';
              eb <= eb - 1;
            else
              state <= F_SYNC;
              if opn = OP_FMUL then
                er  <= ea + eb + 19;
                nxt <= F_MUL;
              elsif opn = OP_FDIV then
                moff <= -40;                        -- mantissas to bits 63..40
                er   <= ea - eb + 38;
                cnt  <= to_unsigned(28, 8);
                nxt  <= F_DIV_LDX;
              else
                if ea mod 2 = 0 then
                  moff <= -31;
                  er   <= ea / 2 + 36;
                else
                  moff <= -32;
                  er   <= (ea - 1) / 2 + 36;
                end if;
                cnt <= to_unsigned(28, 8);
                nxt <= F_SQ_LD;
              end if;
            end if;

          when F_SYNC =>
            if last then
              state <= nxt;
            end if;

          -------------------------------------------------------------------
          when F_ITOF | F_ADD_SUM | F_MUL =>
            if last then
              if state = F_ADD_SUM and rnz = '0' and rdin = '0' then
                sr <= sa and sbe;                   -- exact zero: -0 only for (-0) + (-0)
              end if;
              state <= F_ROUND;
            end if;

          when F_FTOI_LD =>
            if last then state <= F_FTOI_NEG; end if;

          when F_FTOI_NEG =>
            if last then state <= F_FTOI_RES; end if;

          when F_FTOI_RES =>                        -- ph = 0: X lines up with its bits
            res_r <= std_logic_vector(X(31 downto 0));
            state <= F_DONE;

          when F_ADD_LD1 =>
            if last then
              moff  <= to_integer(cnt) - 41;
              state <= F_ADD_LD2;
            end if;

          when F_ADD_LD2 =>
            if last then state <= F_ADD_SUM; end if;

          -------------------------------------------------------------------
          -- fdiv: restoring division, a compare pass and an update pass per bit
          -------------------------------------------------------------------
          when F_DIV_LDX =>
            if last then state <= F_DIV_LDY; end if;

          when F_DIV_LDY =>
            if last then state <= F_DIV_A; end if;

          when F_DIV_A =>
            if last then state <= F_DIV_B; end if;

          when F_DIV_B =>
            if last then
              cnt <= cnt - 1;
              if cnt = 1 then
                if xnz = '1' or xdin = '1' then
                  stk <= '1';                        -- remainder non-zero
                end if;
                state <= F_ROUND;
              else
                state <= F_DIV_A;
              end if;
            end if;

          -------------------------------------------------------------------
          -- sqrt: digit by digit, compare pass and update pass per bit
          -------------------------------------------------------------------
          when F_SQ_LD =>
            if last then state <= F_SQ_A; end if;

          when F_SQ_A =>
            if last then state <= F_SQ_B; end if;

          when F_SQ_B =>
            if last then
              cnt <= cnt - 1;
              if cnt = 1 then
                if ynz = '1' or ydin = '1' then
                  stk <= '1';
                end if;
                state <= F_SQ_END;
              else
                state <= F_SQ_A;
              end if;
            end if;

          when F_SQ_END =>
            if last then state <= F_ROUND; end if;

          -------------------------------------------------------------------
          -- sin / cos / tan
          -------------------------------------------------------------------
          when F_TS_LD =>
            if last then state <= F_TRIG_START; end if;

          when F_PH_WAIT =>
            if j = 39 then
              nn    <= (others => '0');
              state <= F_PH;
            end if;

          when F_PH =>
            -- product bits 26..91 are |a| * 2/pi mod 1 in Q.66 and land in X at the
            -- matching phase; bits 92 and 93 are the two integer bits
            nn <= nn + 1;
            if nn < nt then
              cnt <= cnt - 1;
            end if;
            if nn = 92 then
              t66 <= pbit;
            end if;
            if nn = 93 then
              t67   <= pbit;
              sh    <= to_unsigned(4, 7);
              nxt   <= F_PH_ASR;
              state <= F_SYNC;
            end if;

          when F_PH_ASR =>
            -- nearest quadrant, and the remainder in [-0.5, 0.5) quarter turns to Q3.62
            if j = 0 then
              quad <= (t67 & t66) + ("0" & xs);
            end if;
            if last then
              cnt   <= to_unsigned(64, 8);
              state <= F_PIM;
            end if;

          when F_PIM =>
            -- Z = X * pi/2, pi/2's bits LSB first
            if last then
              if cnt = 0 then
                state <= F_TRIG_START;
              else
                cnt <= cnt - 1;
              end if;
            end if;

          when F_TRIG_START =>
            if j = 0 then
              if Z(65 downto 42) = 0 or not Z(65 downto 42) = 0 then
                tiny <= '1';
              else
                tiny <= '0';
              end if;
            end if;
            if last then
              if tiny = '1' then
                state <= F_TRIG_OUT;
              else
                cnt   <= (others => '0');
                sh    <= (others => '0');
                state <= F_C1;
              end if;
            end if;

          when F_C1 =>
            if last then state <= F_C2; end if;

          when F_C2 =>
            if last then state <= F_C3; end if;

          when F_C3 =>
            if last then
              if cnt = 61 then
                state <= F_TRIG_OUT;
              else
                cnt   <= cnt + 1;
                sh    <= resize(cnt + 1, 7);
                state <= F_C1;
              end if;
            end if;

          when F_TRIG_OUT =>
            -- sin: q0 +sin q1 +cos q2 -sin q3 -cos, then odd in a
            -- cos: q0 +cos q1 -sin q2 -cos q3 +sin
            -- tan: q even +sin/cos, q odd -cos/sin, then odd in a
            if j = 0 then
              if opn = OP_TAN then
                if quad(0) = '0' then
                  nsign := ys;
                  dsign := xs;
                else
                  nsign := xs;
                  dsign := ys;
                end if;
                sr <= nsign xor dsign xor quad(0) xor sa;
              elsif opn = OP_SIN then
                if quad(0) = '0' then v := ys; else v := xs; end if;
                sr <= v xor quad(1) xor sa;
              else
                if quad(0) = '0' then v := xs; else v := ys; end if;
                sr <= v xor (quad(1) xor quad(0));
              end if;
            end if;
            er <= 3;
            if last then
              if opn = OP_TAN then
                state <= F_TAN_D;
              else
                state <= F_ROUND;
              end if;
            end if;

          when F_TAN_D =>
            if last then
              pd    <= pmsb;
              state <= F_TAN_N;
            end if;

          when F_TAN_N =>
            if last then state <= F_TAN_X; end if;

          when F_TAN_X =>
            if last then
              er    <= pmsb - pd + 38;
              state <= F_TAN_Y;
            end if;

          when F_TAN_Y =>
            if last then
              cnt   <= to_unsigned(28, 8);
              stk   <= '0';
              state <= F_DIV_A;
            end if;

          -------------------------------------------------------------------
          -- round R * 2^(er - 65) to nearest even
          -------------------------------------------------------------------
          when F_ROUND =>
            if last then state <= F_PACK; end if;

          when F_PACK =>
            sticky := stk or sbits;
            inc    := gbit and (sticky or mant(0));
            m2     := '0' & mant;
            if inc = '1' then
              m2 := m2 + 1;
            end if;
            e2 := win + er - 42;                    -- exponent if the window's top bit is set
            if m2(24) = '1' then
              m2 := '0' & m2(24 downto 1);
              e2 := e2 + 1;
            end if;
            if rnz = '0' and stk = '0' then
              res_r <= sr & "0000000000000000000000000000000";
            elsif m2(23) = '0' then
              res_r <= sr & "00000000" & std_logic_vector(m2(22 downto 0));
            elsif e2 > 127 then
              res_r <= sr & "1111111100000000000000000000000";
            else
              res_r <= sr & std_logic_vector(to_unsigned(e2 + 127, 8)) & std_logic_vector(m2(22 downto 0));
            end if;
            state <= F_DONE;

          when F_DONE =>
            done_r <= '1';
            state  <= F_IDLE;
        end case;
      end if;
    end if;
  end process;
end architecture;

-------------------------------------------------------------------------------

-- SPI master for the Tiny Tapeout QSPI Pmod (W25Q128 flash + two APS6404L PSRAMs), plain
-- SPI mode 0. Reads use command 0x03, writes 0x02, both with a 24-bit address and no dummy
-- cycles; all three chips understand the 0x03 read. SCK runs at clk/2. Data is little
-- endian: the byte at addr goes into bits 7..0.
-- flash = '1' selects the flash (cs_n(2), read only); otherwise addr(23) picks the PSRAM:
-- 0 -> RAM A (cs_n(0)), 1 -> RAM B (cs_n(1)), giving 16 MiB of RAM.
-- addr, we, size, flash and wdata must stay stable from req until done.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity cupu_spi is
  port (
    clk   : in  std_logic;
    rst   : in  std_logic;
    req   : in  std_logic;
    we    : in  std_logic;
    size  : in  std_logic_vector(1 downto 0);  -- 00 byte, 01 half, 10 word
    addr  : in  std_logic_vector(23 downto 0);
    flash : in  std_logic;
    wdata : in  std_logic_vector(31 downto 0);
    rdata : out std_logic_vector(31 downto 0);
    done  : out std_logic;                     -- one-cycle pulse, rdata valid with it
    sck   : out std_logic;
    mosi  : out std_logic;
    miso  : in  std_logic;
    cs_n  : out std_logic_vector(2 downto 0)
  );
end entity;

architecture rtl of cupu_spi is
  type state_t is (S_IDLE, S_XFER, S_GAP);
  signal state  : state_t;
  signal sreg   : std_logic_vector(31 downto 0);  -- after a read: the data, last byte in 7..0
  signal bitcnt : unsigned(5 downto 0);
  signal sck_r  : std_logic;
  signal cs_r   : std_logic_vector(2 downto 0);
  signal gap    : unsigned(1 downto 0);
  signal last   : unsigned(5 downto 0);
begin
  sck  <= sck_r;
  mosi <= sreg(31);
  cs_n <= cs_r;

  -- the data read, little endian; valid with done and until the next request
  with size select rdata <=
    x"000000" & sreg(7 downto 0)                                          when "00",
    x"0000" & sreg(7 downto 0) & sreg(15 downto 8)                         when "01",
    sreg(7 downto 0) & sreg(15 downto 8) & sreg(23 downto 16) & sreg(31 downto 24) when others;

  -- index of the final bit: 32 command/address bits + 8, 16 or 32 data bits
  with size select last <=
    to_unsigned(39, 6) when "00",
    to_unsigned(47, 6) when "01",
    to_unsigned(63, 6) when others;

  process (clk)
    variable sh : std_logic_vector(31 downto 0);
  begin
    if rising_edge(clk) then
      done <= '0';
      if rst = '1' then
        state <= S_IDLE;
        sck_r <= '0';
        cs_r  <= "111";
      else
        case state is
          when S_IDLE =>
            if req = '1' then
              if we = '1' then
                sreg <= x"02" & addr;
              else
                sreg <= x"03" & addr;
              end if;
              if flash = '1' then
                cs_r <= "011";
              else
                cs_r <= '1' & (not addr(23)) & addr(23);
              end if;
              bitcnt <= (others => '0');
              state  <= S_XFER;
            end if;

          when S_XFER =>
            if sck_r = '0' then
              sck_r <= '1';
            else
              -- falling edge: sample MISO late for pad-delay margin, shift out next bit
              sck_r <= '0';
              sh := sreg(30 downto 0) & miso;
              if bitcnt = last then
                sreg  <= sh;
                cs_r  <= "111";
                done  <= '1';
                gap   <= (others => '1');
                state <= S_GAP;
              else
                if bitcnt = 31 and we = '1' then
                  sreg <= wdata(7 downto 0) & wdata(15 downto 8) & wdata(23 downto 16) & wdata(31 downto 24);
                else
                  sreg <= sh;
                end if;
                bitcnt <= bitcnt + 1;
              end if;
            end if;

          when S_GAP =>
            -- keep CS high for a few cycles (PSRAM tCPH) and drop the requester's stale req
            if gap = 0 then
              state <= S_IDLE;
            else
              gap <= gap - 1;
            end if;
        end case;
      end if;
    end if;
  end process;
end architecture;

-------------------------------------------------------------------------------

-- CUPU-II "Stollentroll" core, multi-cycle implementation of isa.txt.
--
-- Bit-serial: the registers are rings of flops that rotate one bit per clock (see below),
-- and all integer arithmetic goes through one 1-bit adder. An instruction's operands stream
-- out of the rings LSB first in one 32-cycle pass, and add, sub, the logic ops, compares,
-- lui and the jump targets are computed on the way. mul and div take one 33-cycle pass per
-- bit, shifts one cycle per bit. Fetches over SPI take ~130 cycles anyway, so the extra
-- cycles are cheap; the area is not.
-- Floating point ops (func 0x0E..0x17) run in cupu_fpu.
--
-- Differences from the Go emulator are listed in docs/info.md.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity cupu_core is
  generic (
    G_CLK_HZ : natural := 20_000_000  -- for the seconds counter at 0x20000000
  );
  port (
    clk       : in  std_logic;
    rst       : in  std_logic;
    -- external memory (addresses below 0x01000000)
    mem_req   : out std_logic;
    mem_we    : out std_logic;
    mem_size  : out std_logic_vector(1 downto 0);
    mem_addr  : out std_logic_vector(23 downto 0);
    mem_flash : out std_logic;                    -- the access goes to the flash
    mem_wdata : out std_logic_vector(31 downto 0);
    mem_rdata : in  std_logic_vector(31 downto 0);
    mem_done  : in  std_logic;
    -- mmio
    gpio_in   : in  std_logic_vector(7 downto 0);
    gpio_out  : out std_logic_vector(7 downto 0);
    boot      : in  std_logic                     -- start at 0x01000000 (flash) after reset
  );
end entity;

architecture rtl of cupu_core is
  subtype word is unsigned(31 downto 0);
  type ring_t is array (1 to 31) of word;

  type state_t is (
    S_FETCH, S_SYNC, S_RD, S_WB, S_WBJ, S_NEXT, S_MEM, S_FPU,
    S_SH0, S_SH1, S_SH2, S_MUL, S_COPY,
    S_DIV0, S_NEGA, S_NEGB, S_DIV, S_DIVC, S_DIVF,
    S_HALT
  );

  type op_t is (
    OP_NOP, OP_ADD, OP_SUB, OP_MUL, OP_MHI, OP_DIV, OP_DIVU, OP_REM,
    OP_OR, OP_AND, OP_XOR, OP_NOT, OP_SHL, OP_SHR, OP_OVRF, OP_UNRF, OP_FPU,
    OP_CMP, OP_LOAD, OP_STORE, OP_HLT, OP_LUI, OP_JAL, OP_JRAL
  );

  constant MMIO_BASE : unsigned(27 downto 0) := x"2000000";  -- addr(31 downto 4)

  function b2n(b : std_logic) return natural is
  begin
    if b = '1' then return 1; else return 0; end if;
  end function;

  signal state : state_t;
  -- pc, ir: parallel. opa, opb: the operands, shifted in LSB first by the read pass and
  -- then used in parallel (memory address and data, fpu inputs) or as shift registers
  -- (mul, div, shifts). wr_sh: the result, written into its register ring LSB first.
  signal pc, ir, opa, opb, wr_sh : word;
  signal k     : unsigned(5 downto 0);   -- bit within a pass
  signal step  : unsigned(4 downto 0);   -- mul / div step
  signal flag, sgn_q, sgn_r : std_logic;
  signal eqf   : std_logic;              -- read pass: $a equal to the operand so far
  signal nzb   : std_logic;              -- read pass: operand not zero so far
  signal accs, opas, lowb : std_logic;   -- mul: signs of the partial product and $a, product bit
  signal rs, dly, odly    : std_logic;   -- div: remainder sign, remainder / dividend delayed

  -- instruction fields
  signal f_cond : std_logic;
  signal f_opc  : unsigned(4 downto 0);
  signal f_t, f_a, f_b : unsigned(4 downto 0);
  signal f_fn   : unsigned(10 downto 0);
  signal op     : op_t;
  signal op_q   : op_t;                         -- op, registered

  -- register file
  signal rf       : ring_t;                     -- rf(r)(0) is bit `ph` of register r
  signal ph       : unsigned(4 downto 0);       -- phase
  signal taps     : std_logic_vector(0 to 31);  -- taps(0) is $z
  signal rb_idx   : unsigned(4 downto 0);
  signal tap_a    : std_logic;
  signal tap_b    : std_logic;
  signal wr_start : std_logic;
  signal wr_pend  : std_logic;                  -- a write is waiting or running
  signal wr_run   : std_logic;                  -- writing, phase 0..31
  signal wr_all   : std_logic;                  -- clearing all registers after reset
  signal wr_t     : unsigned(4 downto 0);       -- register being written
  signal pc_inc   : word;

  -- serial adder: sum = x + (y xor inv) + z + carry, carry 0..2 (z: jral adds pc as well)
  signal s_x, s_y, s_z, s_inv, s_cin : std_logic;
  signal s_sum  : std_logic;
  signal s_cy   : unsigned(1 downto 0);
  signal cy     : unsigned(1 downto 0);
  signal ir_k, imm_bit, lui_bit, y_rd : std_logic;

  -- memory access
  signal acc_addr  : word;
  signal acc_size  : std_logic_vector(1 downto 0);
  signal acc_req   : std_logic;
  signal mmio_sel  : std_logic;
  signal flash_st  : std_logic;  -- store to the (read only) flash: ignored
  signal mmio_rd   : word;
  signal acc_done  : std_logic;
  signal acc_rdata : word;

  -- fpu
  signal fpu_start : std_logic;
  signal fpu_op    : unsigned(4 downto 0);
  signal fpu_res   : std_logic_vector(31 downto 0);
  signal fpu_done  : std_logic;

  -- mmio devices
  signal gpio      : std_logic_vector(7 downto 0);
  signal seconds   : word;
  signal ts_we     : std_logic;
  signal in_meta   : std_logic_vector(7 downto 0);  -- gpio input synchronizer
  signal in_sync   : std_logic_vector(7 downto 0);
  signal prescale  : natural range 0 to G_CLK_HZ - 1;
begin
  f_cond <= ir(31);
  f_opc  <= ir(30 downto 26);
  f_t    <= ir(25 downto 21);
  f_a    <= ir(20 downto 16);
  f_b    <= ir(15 downto 11);
  f_fn   <= ir(10 downto 0);

  ---------------------------------------------------------------------------
  -- decode
  ---------------------------------------------------------------------------
  process (f_opc, f_fn)
  begin
    op <= OP_NOP;
    if f_opc = 0 then
      case to_integer(f_fn) is
        when 16#00# => op <= OP_ADD;
        when 16#01# => op <= OP_SUB;
        when 16#02# => op <= OP_MUL;
        when 16#03# => op <= OP_DIV;
        when 16#04# => op <= OP_OR;
        when 16#05# => op <= OP_AND;
        when 16#06# => op <= OP_XOR;
        when 16#07# => op <= OP_NOT;
        when 16#08# => op <= OP_SHL;
        when 16#09# => op <= OP_SHR;
        when 16#0A# => op <= OP_REM;
        when 16#0B# => op <= OP_MHI;
        when 16#0C# => op <= OP_OVRF;
        when 16#0D# => op <= OP_UNRF;
        when 16#0E# to 16#17# => op <= OP_FPU;
        when 16#20# to 16#25# => op <= OP_CMP;
        when 16#30# to 16#32# => op <= OP_LOAD;
        when 16#33# to 16#35# => op <= OP_STORE;
        when 16#40# => op <= OP_HLT;
        when others => null;
      end case;
    else
      case to_integer(f_opc) is
        when 16#08# | 16#18# => op <= OP_ADD;
        when 16#09# | 16#19# => op <= OP_SUB;
        when 16#0A# | 16#1A# => op <= OP_MUL;
        when 16#0B#          => op <= OP_DIV;
        when 16#1B#          => op <= OP_DIVU;
        when 16#0C# | 16#1C# => op <= OP_OR;
        when 16#0D# | 16#1D# => op <= OP_AND;
        when 16#0E# | 16#1E# => op <= OP_XOR;
        when 16#0F#          => op <= OP_LUI;
        when 16#10#          => op <= OP_JAL;
        when 16#11#          => op <= OP_JRAL;
        when others => null;
      end case;
    end if;
  end process;

  ---------------------------------------------------------------------------
  -- register file: each register is a ring of 32 flops rotating one bit per clock,
  -- in step with the phase ph, so rf(r)(0) always holds bit ph of register r. The read
  -- pass starts at phase 0 and takes one bit of $a and $b per cycle. Writing $t shifts
  -- the value out of wr_sh into its ring during phases 0..31; it runs in the background
  -- while the next instruction is fetched (which takes longer, so ir and wr_t hold).
  ---------------------------------------------------------------------------
  taps(0) <= '0';
  tap_gen : for r in 1 to 31 generate
    taps(r) <= rf(r)(0);
  end generate;

  rb_idx <= f_t when op_q = OP_STORE else f_b;
  tap_a  <= taps(to_integer(f_a));
  tap_b  <= taps(to_integer(rb_idx));

  wr_start <= '1' when (state = S_WB or state = S_WBJ) and f_t /= 0 else '0';

  process (clk)
  begin
    if rising_edge(clk) then
      if rst = '1' then
        ph      <= (others => '0');
        wr_pend <= '1';                  -- clear all registers, as the emulator starts at 0
        wr_run  <= '0';
        wr_all  <= '1';
      else
        ph <= ph + 1;
        if wr_run = '1' then
          if ph = 31 then
            wr_run  <= '0';
            wr_pend <= '0';
            wr_all  <= '0';
          end if;
        elsif wr_pend = '1' then
          if ph = 31 then
            wr_run <= '1';               -- next cycle is phase 0
          end if;
        elsif wr_start = '1' then
          wr_pend <= '1';
          wr_t    <= f_t;
        end if;
      end if;
    end if;
  end process;

  ring_gen : for r in 1 to 31 generate
    process (clk)
      variable din : std_logic;
    begin
      if rising_edge(clk) then
        din := rf(r)(0);
        if wr_run = '1' and (wr_all = '1' or wr_t = r) then
          din := wr_sh(0);
        end if;
        rf(r) <= din & rf(r)(31 downto 1);
      end if;
    end process;
  end generate;

  pc_inc <= pc + 4;

  ---------------------------------------------------------------------------
  -- serial adder
  ---------------------------------------------------------------------------
  -- bit k of the immediate (sign or zero extended) and of lui's imm << 16
  ir_k    <= ir(to_integer(k(3 downto 0)));
  imm_bit <= ir_k when k(4) = '0' else
             '0'  when f_opc(4 downto 3) = "11" else   -- 0x18..0x1E zero-extend
             ir(15);
  lui_bit <= ir_k when k(4) = '1' else '0';
  y_rd    <= tap_b when f_opc = 0 else imm_bit;        -- the second operand in the read pass

  process (state, op_q, k, step, tap_a, y_rd, pc, opa, opb, wr_sh, accs, opas, rs, dly,
           sgn_q, sgn_r)
  begin
    s_x   <= '0';
    s_y   <= '0';
    s_z   <= '0';
    s_inv <= '0';
    s_cin <= '0';
    case state is
      when S_RD =>
        s_x <= tap_a;
        s_y <= y_rd;
        if op_q = OP_JRAL then
          s_z <= pc(0);                -- pc + $a + imm
        end if;
        case op_q is
          when OP_SUB | OP_UNRF | OP_CMP =>
            s_inv <= '1';
            s_cin <= '1';
          when OP_OVRF =>
            s_cin <= '1';              -- like the emulator: carry of a + b + 1
          when others => null;
        end case;
      when S_MUL =>
        -- partial product (opb, 0 at first) + multiplier bit * $a, 33 bits with sign
        -- extension; the multiplier's sign bit (last step) has negative weight
        if step /= 0 then
          if k(5) = '0' then s_x <= opb(0); else s_x <= accs; end if;
        end if;
        if wr_sh(0) = '1' then
          if k(5) = '0' then s_y <= opa(0); else s_y <= opas; end if;
          if step = 31 then
            s_inv <= '1';
            s_cin <= '1';
          end if;
        end if;
      when S_NEGA =>
        s_y   <= opa(0);
        s_inv <= '1';
        s_cin <= '1';
      when S_NEGB =>
        s_y   <= opb(0);
        s_inv <= '1';
        s_cin <= '1';
      when S_DIV =>
        -- non-restoring: R = 2R + dividend bit -/+ divisor, 33 bits
        if k = 0 then
          s_x <= opa(31);
        elsif step /= 0 then
          s_x <= dly;
        end if;
        if k(5) = '0' then
          s_y <= opb(0);
        end if;
        s_inv <= not rs;
        s_cin <= not rs;
      when S_DIVC =>
        s_x <= wr_sh(0);               -- negative remainder: add the divisor back
        s_y <= opb(0);
      when S_DIVF =>
        if op_q = OP_REM then
          s_y   <= wr_sh(0);
          s_inv <= sgn_r;
          s_cin <= sgn_r;
        else
          s_y   <= opa(0);
          s_inv <= sgn_q;
          s_cin <= sgn_q;
        end if;
      when others => null;
    end case;
  end process;

  process (s_x, s_y, s_z, s_inv, s_cin, cy, k)
    variable t : natural range 0 to 5;
  begin
    if k = 0 then
      t := b2n(s_cin);
    else
      t := to_integer(cy);
    end if;
    t := t + b2n(s_x) + b2n(s_y xor s_inv) + b2n(s_z);
    if t mod 2 = 1 then s_sum <= '1'; else s_sum <= '0'; end if;
    s_cy <= to_unsigned(t / 2, 2);
  end process;

  ---------------------------------------------------------------------------
  -- floating point
  ---------------------------------------------------------------------------
  fpu_op <= f_fn(4 downto 0) - 16#0E#;

  u_fpu : entity work.cupu_fpu
    port map (
      clk   => clk,
      rst   => rst,
      start => fpu_start,
      op    => fpu_op(3 downto 0),
      a     => std_logic_vector(opa),
      b     => std_logic_vector(opb),
      res   => fpu_res,
      done  => fpu_done
    );

  ---------------------------------------------------------------------------
  -- memory access: PSRAM at 0x00000000, flash (read only) at 0x01000000, mmio above
  ---------------------------------------------------------------------------
  acc_addr <= pc when state = S_FETCH else opa;
  acc_req  <= '1' when state = S_FETCH or state = S_MEM else '0';
  process (state, f_fn)
  begin
    if state = S_FETCH then
      acc_size <= "10";
    else
      case f_fn(2 downto 0) is
        when "000" | "011" => acc_size <= "10";  -- lw / sw
        when "001" | "100" => acc_size <= "01";  -- lh / sh
        when others        => acc_size <= "00";  -- lb / sb
      end case;
    end if;
  end process;

  mmio_sel  <= '0' when acc_addr(31 downto 25) = 0 else '1';
  flash_st  <= '1' when mmio_sel = '0' and acc_addr(24) = '1' and state = S_MEM and op_q = OP_STORE else '0';
  mem_req   <= acc_req and not mmio_sel and not flash_st;
  mem_we    <= '1' when state = S_MEM and op_q = OP_STORE else '0';
  mem_size  <= acc_size;
  mem_addr  <= std_logic_vector(acc_addr(23 downto 0));
  mem_flash <= acc_addr(24);
  mem_wdata <= std_logic_vector(opb);
  acc_done  <= mem_done when mmio_sel = '0' and flash_st = '0' else '1';

  -- mmio is read byte by byte like the emulator, so unaligned accesses behave the same
  process (acc_addr, acc_size, seconds, in_sync, gpio)
    variable off : unsigned(4 downto 0);
    variable b   : std_logic_vector(7 downto 0);
    variable r   : std_logic_vector(31 downto 0);
  begin
    r := (others => '0');
    for i in 0 to 3 loop
      off := ('0' & acc_addr(3 downto 0)) + i;
      b   := (others => '0');
      if acc_addr(31 downto 4) = MMIO_BASE then
        case to_integer(off) is
          when 0      => b := std_logic_vector(seconds(7 downto 0));
          when 1      => b := std_logic_vector(seconds(15 downto 8));
          when 2      => b := std_logic_vector(seconds(23 downto 16));
          when 3      => b := std_logic_vector(seconds(31 downto 24));
          when 4      => b := in_sync;
          when 8      => b := gpio;
          when others => null;
        end case;
      end if;
      r(8 * i + 7 downto 8 * i) := b;
    end loop;
    case acc_size is
      when "00"   => r(31 downto 8) := (others => '0');
      when "01"   => r(31 downto 16) := (others => '0');
      when others => null;
    end case;
    mmio_rd <= unsigned(r);
  end process;

  acc_rdata <= unsigned(mem_rdata) when mmio_sel = '0' else mmio_rd;

  gpio_out <= gpio;

  ---------------------------------------------------------------------------
  -- seconds counter: counts from reset; a word store to 0x20000000 sets it
  -- (e.g. to unix time, which is what the emulator returns)
  ---------------------------------------------------------------------------
  ts_we <= '1' when state = S_MEM and op_q = OP_STORE and acc_addr = x"20000000" and acc_size = "10" else '0';

  process (clk)
  begin
    if rising_edge(clk) then
      if rst = '1' then
        prescale <= 0;
        seconds  <= (others => '0');
      elsif ts_we = '1' then
        prescale <= 0;
        seconds  <= opb;
      elsif prescale = G_CLK_HZ - 1 then
        prescale <= 0;
        seconds  <= seconds + 1;
      else
        prescale <= prescale + 1;
      end if;
    end if;
  end process;

  ---------------------------------------------------------------------------
  -- gpio inputs: the ui_in pins, two flops deep since they are asynchronous
  ---------------------------------------------------------------------------
  process (clk)
  begin
    if rising_edge(clk) then
      in_meta <= gpio_in;
      in_sync <= in_meta;
    end if;
  end process;

  ---------------------------------------------------------------------------
  -- control
  ---------------------------------------------------------------------------
  process (clk)
    variable rbit   : std_logic;
    variable ge, eq : std_logic;
    variable signd  : std_logic;
  begin
    if rising_edge(clk) then
      fpu_start <= '0';
      op_q      <= op;
      cy        <= s_cy;
      if wr_run = '1' then
        wr_sh <= '0' & wr_sh(31 downto 1);  -- into the register ring
      end if;
      if op_q = OP_DIVU then signd := '0'; else signd := '1'; end if;

      if rst = '1' then
        state <= S_FETCH;
        if boot = '1' then
          pc <= x"01000000";
        else
          pc <= (others => '0');
        end if;
        flag  <= '0';
        gpio  <= (others => '0');
        wr_sh <= (others => '0');          -- what wr_all clears the registers with
        k     <= (others => '0');
        step  <= (others => '0');
      else
        case state is
          when S_FETCH =>
            if acc_done = '1' then
              ir    <= acc_rdata;
              state <= S_SYNC;
            end if;

          when S_SYNC =>
            -- conditional and the flag is clear: skip. Otherwise wait until the previous
            -- write is in and the rings are at phase 0, then read.
            if f_cond = '1' and flag = '0' then
              state <= S_NEXT;
            elsif wr_pend = '0' and ph = 31 then
              k   <= (others => '0');
              eqf <= '1';
              nzb <= '0';
              if op = OP_JAL or op = OP_JRAL then
                wr_sh <= pc_inc;           -- the link
              end if;
              state <= S_RD;
            end if;

          when S_RD =>
            -- one bit of $a (and $b or the immediate) per cycle; one-pass ops finish here
            k   <= k + 1;
            opa <= tap_a & opa(31 downto 1);
            opb <= y_rd & opb(31 downto 1);
            eqf <= eqf and (tap_a xnor y_rd);
            nzb <= nzb or y_rd;
            case op_q is
              when OP_ADD | OP_SUB  => rbit := s_sum;
              when OP_OR            => rbit := tap_a or y_rd;
              when OP_AND           => rbit := tap_a and y_rd;
              when OP_XOR           => rbit := tap_a xor y_rd;
              when OP_NOT           => rbit := not tap_a;
              when OP_LUI           => rbit := lui_bit;
              when OP_MUL | OP_MHI  => rbit := y_rd;   -- the multiplier
              when others           => rbit := '0';
            end case;
            if op_q = OP_JAL or op_q = OP_JRAL then
              pc <= s_sum & pc(31 downto 1);
            else
              wr_sh <= rbit & wr_sh(31 downto 1);
            end if;

            if k = 31 then
              ge := s_cy(0);             -- no borrow from $a - operand
              eq := eqf and (tap_a xnor y_rd);
              case op_q is
                when OP_ADD | OP_SUB | OP_OR | OP_AND | OP_XOR | OP_NOT | OP_LUI =>
                  state <= S_WB;
                when OP_OVRF =>
                  wr_sh(0) <= s_cy(0);
                  state    <= S_WB;
                when OP_UNRF =>
                  wr_sh(0) <= (not ge) or eq;
                  state    <= S_WB;
                when OP_CMP =>
                  case f_fn(2 downto 0) is
                    when "000"  => flag <= eq;
                    when "001"  => flag <= not eq;
                    when "010"  => flag <= ge and not eq;
                    when "011"  => flag <= ge;
                    when "100"  => flag <= not ge;
                    when others => flag <= (not ge) or eq;
                  end case;
                  state <= S_NEXT;
                when OP_JAL | OP_JRAL =>
                  state <= S_WBJ;
                when OP_LOAD | OP_STORE =>
                  state <= S_MEM;
                when OP_FPU =>
                  fpu_start <= '1';
                  state     <= S_FPU;
                when OP_SHL | OP_SHR =>
                  state <= S_SH0;
                when OP_MUL | OP_MHI =>
                  k     <= (others => '0');
                  step  <= (others => '0');
                  state <= S_MUL;
                when OP_DIV | OP_DIVU | OP_REM =>
                  state <= S_DIV0;
                when OP_HLT =>
                  state <= S_HALT;
                when OP_NOP =>
                  state <= S_NEXT;
              end case;
            end if;

          when S_WB =>
            pc    <= pc_inc;               -- and the write of wr_sh starts (wr_start)
            state <= S_FETCH;

          when S_WBJ =>
            state <= S_FETCH;              -- pc is the target already

          when S_NEXT =>
            pc    <= pc_inc;
            state <= S_FETCH;

          when S_MEM =>
            if acc_done = '1' then
              if op_q = OP_LOAD then
                wr_sh <= acc_rdata;
                state <= S_WB;
              else
                if mmio_sel = '1' and opa = x"20000008" then
                  gpio <= std_logic_vector(opb(7 downto 0));
                end if;
                state <= S_NEXT;
              end if;
            end if;

          when S_FPU =>
            if fpu_done = '1' then
              wr_sh <= unsigned(fpu_res);
              state <= S_WB;
            end if;

          -- shifts: shr drops n bits of $a first, shl puts n zeros in first; then 32 bits
          -- go into wr_sh
          when S_SH0 =>
            k <= (others => '0');
            if opb(31 downto 5) /= 0 then
              wr_sh <= (others => '0');
              state <= S_WB;
            elsif op_q = OP_SHR then
              state <= S_SH1;
            else
              state <= S_SH2;
            end if;

          when S_SH1 =>
            if k(4 downto 0) = opb(4 downto 0) then
              k     <= (others => '0');
              state <= S_SH2;
            else
              opa <= '0' & opa(31 downto 1);
              k   <= k + 1;
            end if;

          when S_SH2 =>
            if op_q = OP_SHL and k(4 downto 0) < opb(4 downto 0) then
              wr_sh <= '0' & wr_sh(31 downto 1);
            else
              wr_sh <= opa(0) & wr_sh(31 downto 1);
              opa   <= '0' & opa(31 downto 1);
            end if;
            k <= k + 1;
            if k = 31 then
              state <= S_WB;
            end if;

          -- mul: 32 steps of 33 cycles. The multiplier is in wr_sh and leaves at the bottom
          -- while the product's low bits come in at the top; the high half builds up in opb.
          when S_MUL =>
            if k = 0 then
              accs <= opb(31);
              opas <= opa(31);
              lowb <= s_sum;
            end if;
            if k(5) = '0' then
              opa <= opa(0) & opa(31 downto 1);   -- rotate
            end if;
            opb <= s_sum & opb(31 downto 1);      -- 33 shifts: sum bits 1..32 stay
            if k = 32 then
              wr_sh <= lowb & wr_sh(31 downto 1);
              k     <= (others => '0');
              step  <= step + 1;
              if step = 31 then
                if op_q = OP_MUL then
                  state <= S_WB;
                else
                  state <= S_COPY;               -- mhi: the high half
                end if;
              end if;
            else
              k <= k + 1;
            end if;

          when S_COPY =>
            wr_sh <= opb(0) & wr_sh(31 downto 1);
            opb   <= opb(0) & opb(31 downto 1);
            k     <= k + 1;
            if k = 31 then
              state <= S_WB;
            end if;

          -- div: divide the magnitudes, quotient into opa, remainder into wr_sh, then fix
          -- the signs (the remainder takes the dividend's, like Go)
          when S_DIV0 =>
            sgn_q <= signd and (opa(31) xor opb(31));
            sgn_r <= signd and opa(31);
            k     <= (others => '0');
            step  <= (others => '0');
            rs    <= '0';
            if nzb = '0' then
              state <= S_HALT;                    -- division by zero: the emulator panics
            elsif signd = '1' and opa(31) = '1' then
              state <= S_NEGA;
            elsif signd = '1' and opb(31) = '1' then
              state <= S_NEGB;
            else
              state <= S_DIV;
            end if;

          when S_NEGA =>
            opa <= s_sum & opa(31 downto 1);
            k   <= k + 1;
            if k = 31 then
              k <= (others => '0');
              if opb(31) = '1' then
                state <= S_NEGB;
              else
                state <= S_DIV;
              end if;
            end if;

          when S_NEGB =>
            opb <= s_sum & opb(31 downto 1);
            k   <= k + 1;
            if k = 31 then
              k     <= (others => '0');
              state <= S_DIV;
            end if;

          when S_DIV =>
            if k(5) = '0' then
              dly   <= wr_sh(0);
              odly  <= opa(0);
              wr_sh <= s_sum & wr_sh(31 downto 1);  -- new remainder bits
              opa   <= odly & opa(31 downto 1);     -- dividend / quotient one to the left
              opb   <= opb(0) & opb(31 downto 1);
              k     <= k + 1;
            else                                    -- bit 32: the new remainder's sign
              rs     <= s_sum;
              opa(0) <= not s_sum;                  -- quotient bit
              k      <= (others => '0');
              step   <= step + 1;
              if step = 31 then
                state <= S_DIVC;
              end if;
            end if;

          when S_DIVC =>
            if rs = '0' then
              state <= S_DIVF;
            else
              wr_sh <= s_sum & wr_sh(31 downto 1);
              opb   <= opb(0) & opb(31 downto 1);
              k     <= k + 1;
              if k = 31 then
                k     <= (others => '0');
                state <= S_DIVF;
              end if;
            end if;

          when S_DIVF =>
            wr_sh <= s_sum & wr_sh(31 downto 1);    -- quotient or remainder, sign fixed
            opa   <= '0' & opa(31 downto 1);
            k     <= k + 1;
            if k = 31 then
              state <= S_WB;
            end if;

          when S_HALT =>
            null;
        end case;
      end if;
    end if;
  end process;
end architecture;

-------------------------------------------------------------------------------

-- Tiny Tapeout top level for CUPU-II.
--
-- ui_in   : gpio inputs, read at 0x20000004 (synchronized, no waiting).
--           ui_in(0) during reset is the boot strap: high starts at 0x01000000 (flash),
--           low at 0 (PSRAM).
-- uo_out  : gpio outputs, written/read back at 0x20000008
-- uio     : TT QSPI Pmod in plain SPI mode (CS0 flash, CS1 RAM A, CS2 RAM B)
--
-- While rst_n is low every uio pin is an input, so the demo board's RP2040 can
-- program the flash or preload the PSRAM before releasing reset.

library ieee;
use ieee.std_logic_1164.all;

entity tt_um_zonlykroks_cupu is
  generic (
    G_CLK_HZ : natural := 20_000_000  -- clock frequency, for the seconds counter
  );
  port (
    ui_in   : in  std_logic_vector(7 downto 0);
    uo_out  : out std_logic_vector(7 downto 0);
    uio_in  : in  std_logic_vector(7 downto 0);
    uio_out : out std_logic_vector(7 downto 0);
    uio_oe  : out std_logic_vector(7 downto 0);
    ena     : in  std_logic;
    clk     : in  std_logic;
    rst_n   : in  std_logic
  );
end entity;

architecture rtl of tt_um_zonlykroks_cupu is
  signal rst, rst_s : std_logic;
  signal boot       : std_logic;

  signal mem_req, mem_we, mem_done : std_logic;
  signal mem_size  : std_logic_vector(1 downto 0);
  signal mem_addr  : std_logic_vector(23 downto 0);
  signal mem_flash : std_logic;
  signal mem_wdata : std_logic_vector(31 downto 0);
  signal mem_rdata : std_logic_vector(31 downto 0);

  signal sck, mosi : std_logic;
  signal cs_n      : std_logic_vector(2 downto 0);
begin
  -- reset synchronizer: keeps the reset pin out of every flop's timing path
  process (clk)
  begin
    if rising_edge(clk) then
      rst_s <= not rst_n;
      rst   <= rst_s;
      -- boot strap: ui_in(0) while the reset pin is low; high runs the program straight
      -- from the flash. Latched here so it may change as soon as reset is released.
      if rst_n = '0' then
        boot <= ui_in(0);
      end if;
    end if;
  end process;

  u_core : entity work.cupu_core
    generic map (G_CLK_HZ => G_CLK_HZ)
    port map (
      clk       => clk,
      rst       => rst,
      mem_req   => mem_req,
      mem_we    => mem_we,
      mem_size  => mem_size,
      mem_addr  => mem_addr,
      mem_flash => mem_flash,
      mem_wdata => mem_wdata,
      mem_rdata => mem_rdata,
      mem_done  => mem_done,
      gpio_in   => ui_in,
      gpio_out  => uo_out,
      boot      => boot
    );

  u_spi : entity work.cupu_spi
    port map (
      clk   => clk,
      rst   => rst,
      req   => mem_req,
      we    => mem_we,
      size  => mem_size,
      addr  => mem_addr,
      flash => mem_flash,
      wdata => mem_wdata,
      rdata => mem_rdata,
      done  => mem_done,
      sck   => sck,
      mosi  => mosi,
      miso  => uio_in(2),
      cs_n  => cs_n
    );

  uio_out(0) <= cs_n(2);  -- flash
  uio_out(1) <= mosi;
  uio_out(2) <= '0';      -- MISO (input)
  uio_out(3) <= sck;
  uio_out(4) <= '1';      -- SD2: flash /WP, PSRAMs ignore it in SPI mode
  uio_out(5) <= '1';      -- SD3: flash /HOLD, must not float low
  uio_out(6) <= cs_n(0);  -- RAM A
  uio_out(7) <= cs_n(1);  -- RAM B

  uio_oe <= x"00" when rst_n = '0' else "11111011";
end architecture;

-------------------------------------------------------------------------------

